2023-09-06 01:56:34,267 INFO    StreamThr :44178 [internal.py:wandb_internal():86] W&B internal server running at pid: 44178, started at: 2023-09-06 01:56:34.266055
2023-09-06 01:56:34,269 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: status
2023-09-06 01:56:34,272 INFO    WriterThread:44178 [datastore.py:open_for_write():85] open: /root/BitFlip/DQNwithHer/outputs/2023-09-06/01-56-32/wandb/run-20230906_015634-pe8qai3n/run-pe8qai3n.wandb
2023-09-06 01:56:34,276 DEBUG   SenderThread:44178 [sender.py:send():379] send: header
2023-09-06 01:56:34,297 DEBUG   SenderThread:44178 [sender.py:send():379] send: run
2023-09-06 01:56:35,093 INFO    SenderThread:44178 [dir_watcher.py:__init__():211] watching files in: /root/BitFlip/DQNwithHer/outputs/2023-09-06/01-56-32/wandb/run-20230906_015634-pe8qai3n/files
2023-09-06 01:56:35,093 INFO    SenderThread:44178 [sender.py:_start_run_threads():1121] run started: pe8qai3n with start time 1693936594.264981
2023-09-06 01:56:35,102 DEBUG   SenderThread:44178 [sender.py:send_request():406] send_request: summary_record
2023-09-06 01:56:35,103 INFO    SenderThread:44178 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2023-09-06 01:56:35,108 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: check_version
2023-09-06 01:56:35,109 DEBUG   SenderThread:44178 [sender.py:send_request():406] send_request: check_version
2023-09-06 01:56:35,412 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: run_start
2023-09-06 01:56:35,424 DEBUG   HandlerThread:44178 [system_info.py:__init__():31] System info init
2023-09-06 01:56:35,424 DEBUG   HandlerThread:44178 [system_info.py:__init__():46] System info init done
2023-09-06 01:56:35,424 INFO    HandlerThread:44178 [system_monitor.py:start():181] Starting system monitor
2023-09-06 01:56:35,424 INFO    SystemMonitor:44178 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-09-06 01:56:35,425 INFO    HandlerThread:44178 [system_monitor.py:probe():201] Collecting system info
2023-09-06 01:56:35,426 INFO    SystemMonitor:44178 [interfaces.py:start():190] Started cpu monitoring
2023-09-06 01:56:35,427 INFO    SystemMonitor:44178 [interfaces.py:start():190] Started disk monitoring
2023-09-06 01:56:35,430 INFO    SystemMonitor:44178 [interfaces.py:start():190] Started gpu monitoring
2023-09-06 01:56:35,433 INFO    SystemMonitor:44178 [interfaces.py:start():190] Started memory monitoring
2023-09-06 01:56:35,438 INFO    SystemMonitor:44178 [interfaces.py:start():190] Started network monitoring
2023-09-06 01:56:35,497 DEBUG   HandlerThread:44178 [system_info.py:probe():195] Probing system
2023-09-06 01:56:35,511 DEBUG   HandlerThread:44178 [system_info.py:_probe_git():180] Probing git
2023-09-06 01:56:35,533 DEBUG   HandlerThread:44178 [system_info.py:_probe_git():188] Probing git done
2023-09-06 01:56:35,533 DEBUG   HandlerThread:44178 [system_info.py:probe():240] Probing system done
2023-09-06 01:56:35,533 DEBUG   HandlerThread:44178 [system_monitor.py:probe():210] {'os': 'Linux-5.4.0-132-generic-x86_64-with-glibc2.35', 'python': '3.9.17', 'heartbeatAt': '2023-09-05T17:56:35.497937', 'startedAt': '2023-09-05T17:56:34.257132', 'docker': None, 'cuda': None, 'args': ('minimal_size=64', 'length=8', 'use_wandb=true', 'epsilon=0.9', 'delta_epsilon=1e-5', 'lr=1e-4'), 'state': 'running', 'program': '/root/BitFlip/DQNwithHer/main.py', 'codePath': 'DQNwithHer/main.py', 'git': {'remote': 'git@github.com:chjchjchjchjchj/BitFlip.git', 'commit': 'de64834fe3b96021cf8ea4590011ec505c48b8c7'}, 'email': 'chjchjchjchjchj2001@gmail.com', 'root': '/root/BitFlip', 'host': 'autodl-container-b06911993c-7c1fab7a', 'username': 'root', 'executable': '/root/miniconda3/envs/ling/bin/python', 'cpu_count': 64, 'cpu_count_logical': 128, 'cpu_freq': {'current': 1215.6170000000004, 'min': 800.0, 'max': 3500.0}, 'cpu_freq_per_core': [{'current': 890.454, 'min': 800.0, 'max': 3500.0}, {'current': 842.231, 'min': 800.0, 'max': 3500.0}, {'current': 800.14, 'min': 800.0, 'max': 3500.0}, {'current': 800.908, 'min': 800.0, 'max': 3500.0}, {'current': 799.685, 'min': 800.0, 'max': 3500.0}, {'current': 787.288, 'min': 800.0, 'max': 3500.0}, {'current': 800.914, 'min': 800.0, 'max': 3500.0}, {'current': 801.357, 'min': 800.0, 'max': 3500.0}, {'current': 800.887, 'min': 800.0, 'max': 3500.0}, {'current': 800.867, 'min': 800.0, 'max': 3500.0}, {'current': 801.347, 'min': 800.0, 'max': 3500.0}, {'current': 807.867, 'min': 800.0, 'max': 3500.0}, {'current': 800.213, 'min': 800.0, 'max': 3500.0}, {'current': 800.357, 'min': 800.0, 'max': 3500.0}, {'current': 800.435, 'min': 800.0, 'max': 3500.0}, {'current': 896.271, 'min': 800.0, 'max': 3500.0}, {'current': 800.413, 'min': 800.0, 'max': 3500.0}, {'current': 2600.002, 'min': 800.0, 'max': 3500.0}, {'current': 1622.68, 'min': 800.0, 'max': 3500.0}, {'current': 2494.507, 'min': 800.0, 'max': 3500.0}, {'current': 888.143, 'min': 800.0, 'max': 3500.0}, {'current': 800.46, 'min': 800.0, 'max': 3500.0}, {'current': 883.501, 'min': 800.0, 'max': 3500.0}, {'current': 840.917, 'min': 800.0, 'max': 3500.0}, {'current': 786.31, 'min': 800.0, 'max': 3500.0}, {'current': 829.166, 'min': 800.0, 'max': 3500.0}, {'current': 801.351, 'min': 800.0, 'max': 3500.0}, {'current': 794.269, 'min': 800.0, 'max': 3500.0}, {'current': 789.878, 'min': 800.0, 'max': 3500.0}, {'current': 801.333, 'min': 800.0, 'max': 3500.0}, {'current': 800.892, 'min': 800.0, 'max': 3500.0}, {'current': 800.514, 'min': 800.0, 'max': 3500.0}, {'current': 800.683, 'min': 800.0, 'max': 3500.0}, {'current': 800.688, 'min': 800.0, 'max': 3500.0}, {'current': 3079.206, 'min': 800.0, 'max': 3500.0}, {'current': 1800.002, 'min': 800.0, 'max': 3500.0}, {'current': 1801.195, 'min': 800.0, 'max': 3500.0}, {'current': 800.0, 'min': 800.0, 'max': 3500.0}, {'current': 800.676, 'min': 800.0, 'max': 3500.0}, {'current': 1101.16, 'min': 800.0, 'max': 3500.0}, {'current': 1700.002, 'min': 800.0, 'max': 3500.0}, {'current': 2600.0, 'min': 800.0, 'max': 3500.0}, {'current': 1803.607, 'min': 800.0, 'max': 3500.0}, {'current': 1102.01, 'min': 800.0, 'max': 3500.0}, {'current': 1103.665, 'min': 800.0, 'max': 3500.0}, {'current': 1800.0, 'min': 800.0, 'max': 3500.0}, {'current': 800.0, 'min': 800.0, 'max': 3500.0}, {'current': 1842.325, 'min': 800.0, 'max': 3500.0}, {'current': 1800.005, 'min': 800.0, 'max': 3500.0}, {'current': 1536.738, 'min': 800.0, 'max': 3500.0}, {'current': 800.0, 'min': 800.0, 'max': 3500.0}, {'current': 799.975, 'min': 800.0, 'max': 3500.0}, {'current': 3190.522, 'min': 800.0, 'max': 3500.0}, {'current': 800.0, 'min': 800.0, 'max': 3500.0}, {'current': 1799.244, 'min': 800.0, 'max': 3500.0}, {'current': 800.991, 'min': 800.0, 'max': 3500.0}, {'current': 900.0, 'min': 800.0, 'max': 3500.0}, {'current': 1343.272, 'min': 800.0, 'max': 3500.0}, {'current': 800.0, 'min': 800.0, 'max': 3500.0}, {'current': 801.008, 'min': 800.0, 'max': 3500.0}, {'current': 801.001, 'min': 800.0, 'max': 3500.0}, {'current': 1700.002, 'min': 800.0, 'max': 3500.0}, {'current': 801.007, 'min': 800.0, 'max': 3500.0}, {'current': 1800.562, 'min': 800.0, 'max': 3500.0}, {'current': 856.608, 'min': 800.0, 'max': 3500.0}, {'current': 831.48, 'min': 800.0, 'max': 3500.0}, {'current': 800.948, 'min': 800.0, 'max': 3500.0}, {'current': 800.98, 'min': 800.0, 'max': 3500.0}, {'current': 800.46, 'min': 800.0, 'max': 3500.0}, {'current': 848.111, 'min': 800.0, 'max': 3500.0}, {'current': 800.162, 'min': 800.0, 'max': 3500.0}, {'current': 815.499, 'min': 800.0, 'max': 3500.0}, {'current': 917.073, 'min': 800.0, 'max': 3500.0}, {'current': 800.334, 'min': 800.0, 'max': 3500.0}, {'current': 800.984, 'min': 800.0, 'max': 3500.0}, {'current': 883.876, 'min': 800.0, 'max': 3500.0}, {'current': 821.03, 'min': 800.0, 'max': 3500.0}, {'current': 800.98, 'min': 800.0, 'max': 3500.0}, {'current': 874.221, 'min': 800.0, 'max': 3500.0}, {'current': 867.697, 'min': 800.0, 'max': 3500.0}, {'current': 800.972, 'min': 800.0, 'max': 3500.0}, {'current': 2596.5, 'min': 800.0, 'max': 3500.0}, {'current': 1681.081, 'min': 800.0, 'max': 3500.0}, {'current': 2344.854, 'min': 800.0, 'max': 3500.0}, {'current': 901.77, 'min': 800.0, 'max': 3500.0}, {'current': 801.215, 'min': 800.0, 'max': 3500.0}, {'current': 843.01, 'min': 800.0, 'max': 3500.0}, {'current': 818.424, 'min': 800.0, 'max': 3500.0}, {'current': 841.704, 'min': 800.0, 'max': 3500.0}, {'current': 806.561, 'min': 800.0, 'max': 3500.0}, {'current': 801.836, 'min': 800.0, 'max': 3500.0}, {'current': 852.149, 'min': 800.0, 'max': 3500.0}, {'current': 861.84, 'min': 800.0, 'max': 3500.0}, {'current': 800.911, 'min': 800.0, 'max': 3500.0}, {'current': 801.372, 'min': 800.0, 'max': 3500.0}, {'current': 801.356, 'min': 800.0, 'max': 3500.0}, {'current': 800.0, 'min': 800.0, 'max': 3500.0}, {'current': 800.0, 'min': 800.0, 'max': 3500.0}, {'current': 2982.03, 'min': 800.0, 'max': 3500.0}, {'current': 1804.931, 'min': 800.0, 'max': 3500.0}, {'current': 1797.723, 'min': 800.0, 'max': 3500.0}, {'current': 900.0, 'min': 800.0, 'max': 3500.0}, {'current': 799.386, 'min': 800.0, 'max': 3500.0}, {'current': 1100.465, 'min': 800.0, 'max': 3500.0}, {'current': 1704.419, 'min': 800.0, 'max': 3500.0}, {'current': 2600.0, 'min': 800.0, 'max': 3500.0}, {'current': 1797.287, 'min': 800.0, 'max': 3500.0}, {'current': 1100.686, 'min': 800.0, 'max': 3500.0}, {'current': 1300.404, 'min': 800.0, 'max': 3500.0}, {'current': 1801.597, 'min': 800.0, 'max': 3500.0}, {'current': 800.962, 'min': 800.0, 'max': 3500.0}, {'current': 1882.099, 'min': 800.0, 'max': 3500.0}, {'current': 1800.0, 'min': 800.0, 'max': 3500.0}, {'current': 1797.236, 'min': 800.0, 'max': 3500.0}, {'current': 798.992, 'min': 800.0, 'max': 3500.0}, {'current': 800.0, 'min': 800.0, 'max': 3500.0}, {'current': 3116.921, 'min': 800.0, 'max': 3500.0}, {'current': 800.0, 'min': 800.0, 'max': 3500.0}, {'current': 1300.421, 'min': 800.0, 'max': 3500.0}, {'current': 800.0, 'min': 800.0, 'max': 3500.0}, {'current': 801.02, 'min': 800.0, 'max': 3500.0}, {'current': 1701.918, 'min': 800.0, 'max': 3500.0}, {'current': 800.0, 'min': 800.0, 'max': 3500.0}, {'current': 798.971, 'min': 800.0, 'max': 3500.0}, {'current': 800.0, 'min': 800.0, 'max': 3500.0}, {'current': 1700.316, 'min': 800.0, 'max': 3500.0}, {'current': 800.0, 'min': 800.0, 'max': 3500.0}, {'current': 2010.175, 'min': 800.0, 'max': 3500.0}], 'disk': {'total': 30.0, 'used': 11.08328628540039}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 4, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 377.53807830810547}}
2023-09-06 01:56:35,534 INFO    HandlerThread:44178 [system_monitor.py:probe():211] Finished collecting system info
2023-09-06 01:56:35,534 INFO    HandlerThread:44178 [system_monitor.py:probe():214] Publishing system info
2023-09-06 01:56:35,534 DEBUG   HandlerThread:44178 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-09-06 01:56:35,534 DEBUG   HandlerThread:44178 [system_info.py:_save_pip():67] Saving pip packages done
2023-09-06 01:56:35,534 DEBUG   HandlerThread:44178 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-09-06 01:56:35,541 ERROR   HandlerThread:44178 [system_info.py:_save_conda():85] Error saving conda packages: [Errno 2] No such file or directory: 'conda'
Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/system/system_info.py", line 81, in _save_conda
    subprocess.call(
  File "/root/miniconda3/envs/ling/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/root/miniconda3/envs/ling/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/root/miniconda3/envs/ling/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'conda'
2023-09-06 01:56:35,542 DEBUG   HandlerThread:44178 [system_info.py:_save_conda():86] Saving conda packages done
2023-09-06 01:56:35,544 INFO    HandlerThread:44178 [system_monitor.py:probe():216] Finished publishing system info
2023-09-06 01:56:35,550 DEBUG   SenderThread:44178 [sender.py:send():379] send: files
2023-09-06 01:56:35,551 INFO    SenderThread:44178 [sender.py:_save_file():1375] saving file wandb-metadata.json with policy now
2023-09-06 01:56:35,564 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: stop_status
2023-09-06 01:56:35,564 DEBUG   SenderThread:44178 [sender.py:send_request():406] send_request: stop_status
2023-09-06 01:56:36,038 DEBUG   SenderThread:44178 [sender.py:send():379] send: telemetry
2023-09-06 01:56:36,097 INFO    Thread-12 :44178 [dir_watcher.py:_on_file_created():271] file/dir created: /root/BitFlip/DQNwithHer/outputs/2023-09-06/01-56-32/wandb/run-20230906_015634-pe8qai3n/files/wandb-summary.json
2023-09-06 01:56:36,098 INFO    Thread-12 :44178 [dir_watcher.py:_on_file_created():271] file/dir created: /root/BitFlip/DQNwithHer/outputs/2023-09-06/01-56-32/wandb/run-20230906_015634-pe8qai3n/files/output.log
2023-09-06 01:56:36,098 INFO    Thread-12 :44178 [dir_watcher.py:_on_file_created():271] file/dir created: /root/BitFlip/DQNwithHer/outputs/2023-09-06/01-56-32/wandb/run-20230906_015634-pe8qai3n/files/wandb-metadata.json
2023-09-06 01:56:36,098 INFO    Thread-12 :44178 [dir_watcher.py:_on_file_created():271] file/dir created: /root/BitFlip/DQNwithHer/outputs/2023-09-06/01-56-32/wandb/run-20230906_015634-pe8qai3n/files/conda-environment.yaml
2023-09-06 01:56:36,098 INFO    Thread-12 :44178 [dir_watcher.py:_on_file_created():271] file/dir created: /root/BitFlip/DQNwithHer/outputs/2023-09-06/01-56-32/wandb/run-20230906_015634-pe8qai3n/files/requirements.txt
2023-09-06 01:56:36,163 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/pe8qai3n/wandb-metadata.json?Expires=1694022995&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=PDKSxivXtSmoKs71EcThGBaVC67GjikFHofxZ4axYYrHY%2BVCrLjXkkNwq%2BdKqvWT1%2BdT%2FPX4%2BMxTnG8gXQr0%2FLQR9abMFQmz08NyR%2BR2xyjn%2FnXAlNAxpl%2FQM2hoZu6odCUb%2BrqWj46MEbbNugmFL%2Bb8PEkaMXPt6A0mWb1cTBYVoBOQUDNAO4T7h%2F07g1kqJFTEBHAQehsadiyjzl2GMim1pdwYASalxqFAk8yr%2FaSTHYEyZ32d%2FCKzu%2FKOC0kHMGDBBQKfaGfut9AKvVLUweivTc2b1JLSNlDZwwK3B77IxrjGeg3HuUCVgC2EJad5osuWtHTHR5eAlmpW1s4Q1A%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 01:56:36,163 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15125'}
2023-09-06 01:56:36,163 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 01:56:37,302 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/pe8qai3n/wandb-metadata.json?Expires=1694022995&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=PDKSxivXtSmoKs71EcThGBaVC67GjikFHofxZ4axYYrHY%2BVCrLjXkkNwq%2BdKqvWT1%2BdT%2FPX4%2BMxTnG8gXQr0%2FLQR9abMFQmz08NyR%2BR2xyjn%2FnXAlNAxpl%2FQM2hoZu6odCUb%2BrqWj46MEbbNugmFL%2Bb8PEkaMXPt6A0mWb1cTBYVoBOQUDNAO4T7h%2F07g1kqJFTEBHAQehsadiyjzl2GMim1pdwYASalxqFAk8yr%2FaSTHYEyZ32d%2FCKzu%2FKOC0kHMGDBBQKfaGfut9AKvVLUweivTc2b1JLSNlDZwwK3B77IxrjGeg3HuUCVgC2EJad5osuWtHTHR5eAlmpW1s4Q1A%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 01:56:37,302 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15125'}
2023-09-06 01:56:37,302 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 01:56:37,949 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: partial_history
2023-09-06 01:56:37,953 DEBUG   SenderThread:44178 [sender.py:send():379] send: history
2023-09-06 01:56:37,953 DEBUG   SenderThread:44178 [sender.py:send_request():406] send_request: summary_record
2023-09-06 01:56:37,955 INFO    SenderThread:44178 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2023-09-06 01:56:38,095 INFO    Thread-12 :44178 [dir_watcher.py:_on_file_modified():288] file/dir modified: /root/BitFlip/DQNwithHer/outputs/2023-09-06/01-56-32/wandb/run-20230906_015634-pe8qai3n/files/wandb-summary.json
2023-09-06 01:56:38,096 INFO    Thread-12 :44178 [dir_watcher.py:_on_file_modified():288] file/dir modified: /root/BitFlip/DQNwithHer/outputs/2023-09-06/01-56-32/wandb/run-20230906_015634-pe8qai3n/files/output.log
2023-09-06 01:56:38,158 DEBUG   SenderThread:44178 [sender.py:send():379] send: exit
2023-09-06 01:56:38,158 INFO    SenderThread:44178 [sender.py:send_exit():584] handling exit code: 1
2023-09-06 01:56:38,160 INFO    SenderThread:44178 [sender.py:send_exit():586] handling runtime: 2
2023-09-06 01:56:38,161 INFO    SenderThread:44178 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2023-09-06 01:56:38,162 INFO    SenderThread:44178 [sender.py:send_exit():592] send defer
2023-09-06 01:56:38,162 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: defer
2023-09-06 01:56:38,163 INFO    HandlerThread:44178 [handler.py:handle_request_defer():170] handle defer: 0
2023-09-06 01:56:38,163 DEBUG   SenderThread:44178 [sender.py:send_request():406] send_request: defer
2023-09-06 01:56:38,163 INFO    SenderThread:44178 [sender.py:send_request_defer():608] handle sender defer: 0
2023-09-06 01:56:38,163 INFO    SenderThread:44178 [sender.py:transition_state():612] send defer: 1
2023-09-06 01:56:38,164 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: defer
2023-09-06 01:56:38,164 INFO    HandlerThread:44178 [handler.py:handle_request_defer():170] handle defer: 1
2023-09-06 01:56:38,165 DEBUG   SenderThread:44178 [sender.py:send_request():406] send_request: defer
2023-09-06 01:56:38,165 INFO    SenderThread:44178 [sender.py:send_request_defer():608] handle sender defer: 1
2023-09-06 01:56:38,165 INFO    SenderThread:44178 [sender.py:transition_state():612] send defer: 2
2023-09-06 01:56:38,165 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: defer
2023-09-06 01:56:38,165 INFO    HandlerThread:44178 [handler.py:handle_request_defer():170] handle defer: 2
2023-09-06 01:56:38,166 INFO    HandlerThread:44178 [system_monitor.py:finish():190] Stopping system monitor
2023-09-06 01:56:38,166 DEBUG   SystemMonitor:44178 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-09-06 01:56:38,167 DEBUG   SystemMonitor:44178 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-09-06 01:56:38,168 DEBUG   SystemMonitor:44178 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-09-06 01:56:38,168 INFO    HandlerThread:44178 [interfaces.py:finish():202] Joined cpu monitor
2023-09-06 01:56:38,174 INFO    HandlerThread:44178 [interfaces.py:finish():202] Joined disk monitor
2023-09-06 01:56:38,211 INFO    HandlerThread:44178 [interfaces.py:finish():202] Joined gpu monitor
2023-09-06 01:56:38,212 INFO    HandlerThread:44178 [interfaces.py:finish():202] Joined memory monitor
2023-09-06 01:56:38,212 INFO    HandlerThread:44178 [interfaces.py:finish():202] Joined network monitor
2023-09-06 01:56:38,213 DEBUG   SenderThread:44178 [sender.py:send_request():406] send_request: defer
2023-09-06 01:56:38,214 INFO    SenderThread:44178 [sender.py:send_request_defer():608] handle sender defer: 2
2023-09-06 01:56:38,214 INFO    SenderThread:44178 [sender.py:transition_state():612] send defer: 3
2023-09-06 01:56:38,214 DEBUG   SenderThread:44178 [sender.py:send():379] send: stats
2023-09-06 01:56:38,217 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: defer
2023-09-06 01:56:38,217 INFO    HandlerThread:44178 [handler.py:handle_request_defer():170] handle defer: 3
2023-09-06 01:56:38,218 DEBUG   SenderThread:44178 [sender.py:send_request():406] send_request: defer
2023-09-06 01:56:38,218 INFO    SenderThread:44178 [sender.py:send_request_defer():608] handle sender defer: 3
2023-09-06 01:56:38,218 INFO    SenderThread:44178 [sender.py:transition_state():612] send defer: 4
2023-09-06 01:56:38,218 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: defer
2023-09-06 01:56:38,219 INFO    HandlerThread:44178 [handler.py:handle_request_defer():170] handle defer: 4
2023-09-06 01:56:38,219 DEBUG   SenderThread:44178 [sender.py:send_request():406] send_request: defer
2023-09-06 01:56:38,219 INFO    SenderThread:44178 [sender.py:send_request_defer():608] handle sender defer: 4
2023-09-06 01:56:38,219 INFO    SenderThread:44178 [sender.py:transition_state():612] send defer: 5
2023-09-06 01:56:38,220 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: defer
2023-09-06 01:56:38,220 INFO    HandlerThread:44178 [handler.py:handle_request_defer():170] handle defer: 5
2023-09-06 01:56:38,221 DEBUG   SenderThread:44178 [sender.py:send():379] send: summary
2023-09-06 01:56:38,222 INFO    SenderThread:44178 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2023-09-06 01:56:38,222 DEBUG   SenderThread:44178 [sender.py:send_request():406] send_request: defer
2023-09-06 01:56:38,222 INFO    SenderThread:44178 [sender.py:send_request_defer():608] handle sender defer: 5
2023-09-06 01:56:38,223 INFO    SenderThread:44178 [sender.py:transition_state():612] send defer: 6
2023-09-06 01:56:38,223 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: defer
2023-09-06 01:56:38,223 INFO    HandlerThread:44178 [handler.py:handle_request_defer():170] handle defer: 6
2023-09-06 01:56:38,224 DEBUG   SenderThread:44178 [sender.py:send_request():406] send_request: defer
2023-09-06 01:56:38,224 INFO    SenderThread:44178 [sender.py:send_request_defer():608] handle sender defer: 6
2023-09-06 01:56:38,229 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: status_report
2023-09-06 01:56:38,525 INFO    SenderThread:44178 [sender.py:transition_state():612] send defer: 7
2023-09-06 01:56:38,525 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: defer
2023-09-06 01:56:38,525 INFO    HandlerThread:44178 [handler.py:handle_request_defer():170] handle defer: 7
2023-09-06 01:56:38,526 DEBUG   SenderThread:44178 [sender.py:send_request():406] send_request: defer
2023-09-06 01:56:38,527 INFO    SenderThread:44178 [sender.py:send_request_defer():608] handle sender defer: 7
2023-09-06 01:56:39,096 INFO    Thread-12 :44178 [dir_watcher.py:_on_file_modified():288] file/dir modified: /root/BitFlip/DQNwithHer/outputs/2023-09-06/01-56-32/wandb/run-20230906_015634-pe8qai3n/files/wandb-summary.json
2023-09-06 01:56:39,097 INFO    Thread-12 :44178 [dir_watcher.py:_on_file_modified():288] file/dir modified: /root/BitFlip/DQNwithHer/outputs/2023-09-06/01-56-32/wandb/run-20230906_015634-pe8qai3n/files/config.yaml
2023-09-06 01:56:39,159 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: poll_exit
2023-09-06 01:56:40,096 INFO    Thread-12 :44178 [dir_watcher.py:_on_file_modified():288] file/dir modified: /root/BitFlip/DQNwithHer/outputs/2023-09-06/01-56-32/wandb/run-20230906_015634-pe8qai3n/files/output.log
2023-09-06 01:56:41,957 INFO    SenderThread:44178 [sender.py:transition_state():612] send defer: 8
2023-09-06 01:56:41,958 DEBUG   SenderThread:44178 [sender.py:send_request():406] send_request: poll_exit
2023-09-06 01:56:41,958 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: defer
2023-09-06 01:56:41,958 INFO    HandlerThread:44178 [handler.py:handle_request_defer():170] handle defer: 8
2023-09-06 01:56:41,959 DEBUG   SenderThread:44178 [sender.py:send_request():406] send_request: defer
2023-09-06 01:56:41,959 INFO    SenderThread:44178 [sender.py:send_request_defer():608] handle sender defer: 8
2023-09-06 01:56:41,960 INFO    SenderThread:44178 [job_builder.py:build():281] Attempting to build job artifact
2023-09-06 01:56:41,961 INFO    SenderThread:44178 [job_builder.py:_get_source_type():400] is repo sourced job
2023-09-06 01:56:41,964 INFO    SenderThread:44178 [job_builder.py:build():374] adding wandb-job metadata file
2023-09-06 01:56:41,969 INFO    SenderThread:44178 [sender.py:transition_state():612] send defer: 9
2023-09-06 01:56:41,969 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: defer
2023-09-06 01:56:41,969 INFO    HandlerThread:44178 [handler.py:handle_request_defer():170] handle defer: 9
2023-09-06 01:56:41,970 DEBUG   SenderThread:44178 [sender.py:send():379] send: artifact
2023-09-06 01:56:42,098 INFO    Thread-12 :44178 [dir_watcher.py:_on_file_modified():288] file/dir modified: /root/BitFlip/DQNwithHer/outputs/2023-09-06/01-56-32/wandb/run-20230906_015634-pe8qai3n/files/output.log
2023-09-06 01:56:43,420 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/559989766/a37748b2bbe2fd6ee2a914aedbbdac1f?Expires=1694023003&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IhgEdfFvPG6Y2sW7ocroFiVsqTDHIs%2FmUwXRgsG92Qzn1hROt1hw%2FASznkPBYpOIGZ7vdGxXxbW4JuXGZUVDZza2C6einZaDri9AHi5U32xTTre76yxPZnYiyBAFuq7uFe1AGtarPA3IwN4tMQ%2FYCgdl449t0IarnIq74aCNX9HiRYPyFznho%2Bx%2BEzAjIE%2F8aURKyUDbOyEeqshnyXZTce1cui3Kvb8phroPzC2InFIL2ZZjU9IxtiaZjSSYwgnR9KnkvMjbtyzP1bA4BMyrPvTCqzD%2BraNzjn%2FGJ0ypgAV%2FMR89x0qevmQLF0vpxv2NaGFSk62b2rQJ2VpZFnBGcA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 01:56:43,420 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'o3dIsrvi/W7iqRSu272sHw==', 'Content-Type': 'application/json', 'Content-Length': '3078'}
2023-09-06 01:56:43,420 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 01:56:43,431 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/559989766/5366b528953a1441ad7f8f84d022595f?Expires=1694023003&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jl94doxpmR4cIiVtF8CDtpgh9IB95Asn6BqfNG5mTQH8b3bv%2BzNi0dRvsxdQXWq0KUJDDZ4XjYrIg7Lyd1TlyjsVLgNkWg3Av7EOfOiUhDZ0QJ2skvMttt384hWu44E60Siss1yD2238OlnF9GOBOCRaImDehGtih9jsjX68K7%2BgSl9L5UONOzaXCeaqrWvwPTVohuiWE1lTWXGkLR70zzzJtg9cPs3GhHh2vwohWKIB68AZMeziNoEtsEKJBDcX9wflprSC8GO96r67PsKq7JwOPpQl%2BU5hZ6LA2K82Ac8C7KJX8gsfqwt3e7ULv5YURV0j%2FopWuQM3En6fbIhmQA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 01:56:43,431 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 01:56:43,431 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 01:56:44,161 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: keepalive
2023-09-06 01:56:44,573 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/559989766/5366b528953a1441ad7f8f84d022595f?Expires=1694023003&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jl94doxpmR4cIiVtF8CDtpgh9IB95Asn6BqfNG5mTQH8b3bv%2BzNi0dRvsxdQXWq0KUJDDZ4XjYrIg7Lyd1TlyjsVLgNkWg3Av7EOfOiUhDZ0QJ2skvMttt384hWu44E60Siss1yD2238OlnF9GOBOCRaImDehGtih9jsjX68K7%2BgSl9L5UONOzaXCeaqrWvwPTVohuiWE1lTWXGkLR70zzzJtg9cPs3GhHh2vwohWKIB68AZMeziNoEtsEKJBDcX9wflprSC8GO96r67PsKq7JwOPpQl%2BU5hZ6LA2K82Ac8C7KJX8gsfqwt3e7ULv5YURV0j%2FopWuQM3En6fbIhmQA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 01:56:44,574 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 01:56:44,574 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 01:56:46,976 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/559989766/5366b528953a1441ad7f8f84d022595f?Expires=1694023003&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jl94doxpmR4cIiVtF8CDtpgh9IB95Asn6BqfNG5mTQH8b3bv%2BzNi0dRvsxdQXWq0KUJDDZ4XjYrIg7Lyd1TlyjsVLgNkWg3Av7EOfOiUhDZ0QJ2skvMttt384hWu44E60Siss1yD2238OlnF9GOBOCRaImDehGtih9jsjX68K7%2BgSl9L5UONOzaXCeaqrWvwPTVohuiWE1lTWXGkLR70zzzJtg9cPs3GhHh2vwohWKIB68AZMeziNoEtsEKJBDcX9wflprSC8GO96r67PsKq7JwOPpQl%2BU5hZ6LA2K82Ac8C7KJX8gsfqwt3e7ULv5YURV0j%2FopWuQM3En6fbIhmQA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 01:56:46,976 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 01:56:46,976 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 01:56:46,976 INFO    wandb-upload_1:44178 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2491, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2520, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2491, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2023-09-06 01:56:49,163 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: keepalive
2023-09-06 01:56:54,166 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: keepalive
2023-09-06 01:56:59,168 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: keepalive
2023-09-06 01:57:04,170 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: keepalive
2023-09-06 01:57:09,172 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: keepalive
2023-09-06 01:57:14,174 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: keepalive
2023-09-06 01:57:19,176 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: keepalive
2023-09-06 01:57:23,327 WARNING StreamThr :44178 [internal.py:is_dead():414] Internal process exiting, parent pid 44134 disappeared
2023-09-06 01:57:23,328 ERROR   StreamThr :44178 [internal.py:wandb_internal():152] Internal process shutdown.
2023-09-06 01:57:23,977 INFO    WriterThread:44178 [datastore.py:close():294] close: /root/BitFlip/DQNwithHer/outputs/2023-09-06/01-56-32/wandb/run-20230906_015634-pe8qai3n/run-pe8qai3n.wandb
2023-09-06 01:57:24,177 DEBUG   HandlerThread:44178 [handler.py:handle_request():144] handle_request: keepalive
2023-09-06 01:57:24,177 INFO    HandlerThread:44178 [handler.py:finish():861] shutting down handler
2023-09-06 01:58:49,304 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/pe8qai3n/wandb-metadata.json?Expires=1694022995&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=PDKSxivXtSmoKs71EcThGBaVC67GjikFHofxZ4axYYrHY%2BVCrLjXkkNwq%2BdKqvWT1%2BdT%2FPX4%2BMxTnG8gXQr0%2FLQR9abMFQmz08NyR%2BR2xyjn%2FnXAlNAxpl%2FQM2hoZu6odCUb%2BrqWj46MEbbNugmFL%2Bb8PEkaMXPt6A0mWb1cTBYVoBOQUDNAO4T7h%2F07g1kqJFTEBHAQehsadiyjzl2GMim1pdwYASalxqFAk8yr%2FaSTHYEyZ32d%2FCKzu%2FKOC0kHMGDBBQKfaGfut9AKvVLUweivTc2b1JLSNlDZwwK3B77IxrjGeg3HuUCVgC2EJad5osuWtHTHR5eAlmpW1s4Q1A%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 01:58:49,305 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15125'}
2023-09-06 01:58:49,305 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 01:58:49,305 INFO    wandb-upload_0:44178 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2491, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2520, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2491, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2023-09-06 01:58:54,367 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/pe8qai3n/wandb-metadata.json?Expires=1694022995&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=PDKSxivXtSmoKs71EcThGBaVC67GjikFHofxZ4axYYrHY%2BVCrLjXkkNwq%2BdKqvWT1%2BdT%2FPX4%2BMxTnG8gXQr0%2FLQR9abMFQmz08NyR%2BR2xyjn%2FnXAlNAxpl%2FQM2hoZu6odCUb%2BrqWj46MEbbNugmFL%2Bb8PEkaMXPt6A0mWb1cTBYVoBOQUDNAO4T7h%2F07g1kqJFTEBHAQehsadiyjzl2GMim1pdwYASalxqFAk8yr%2FaSTHYEyZ32d%2FCKzu%2FKOC0kHMGDBBQKfaGfut9AKvVLUweivTc2b1JLSNlDZwwK3B77IxrjGeg3HuUCVgC2EJad5osuWtHTHR5eAlmpW1s4Q1A%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 01:58:54,368 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15125'}
2023-09-06 01:58:54,368 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 01:58:55,589 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/559989766/a37748b2bbe2fd6ee2a914aedbbdac1f?Expires=1694023003&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IhgEdfFvPG6Y2sW7ocroFiVsqTDHIs%2FmUwXRgsG92Qzn1hROt1hw%2FASznkPBYpOIGZ7vdGxXxbW4JuXGZUVDZza2C6einZaDri9AHi5U32xTTre76yxPZnYiyBAFuq7uFe1AGtarPA3IwN4tMQ%2FYCgdl449t0IarnIq74aCNX9HiRYPyFznho%2Bx%2BEzAjIE%2F8aURKyUDbOyEeqshnyXZTce1cui3Kvb8phroPzC2InFIL2ZZjU9IxtiaZjSSYwgnR9KnkvMjbtyzP1bA4BMyrPvTCqzD%2BraNzjn%2FGJ0ypgAV%2FMR89x0qevmQLF0vpxv2NaGFSk62b2rQJ2VpZFnBGcA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 01:58:55,590 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'o3dIsrvi/W7iqRSu272sHw==', 'Content-Type': 'application/json', 'Content-Length': '3078'}
2023-09-06 01:58:55,590 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 01:58:57,726 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/559989766/a37748b2bbe2fd6ee2a914aedbbdac1f?Expires=1694023003&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IhgEdfFvPG6Y2sW7ocroFiVsqTDHIs%2FmUwXRgsG92Qzn1hROt1hw%2FASznkPBYpOIGZ7vdGxXxbW4JuXGZUVDZza2C6einZaDri9AHi5U32xTTre76yxPZnYiyBAFuq7uFe1AGtarPA3IwN4tMQ%2FYCgdl449t0IarnIq74aCNX9HiRYPyFznho%2Bx%2BEzAjIE%2F8aURKyUDbOyEeqshnyXZTce1cui3Kvb8phroPzC2InFIL2ZZjU9IxtiaZjSSYwgnR9KnkvMjbtyzP1bA4BMyrPvTCqzD%2BraNzjn%2FGJ0ypgAV%2FMR89x0qevmQLF0vpxv2NaGFSk62b2rQJ2VpZFnBGcA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 01:58:57,726 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'o3dIsrvi/W7iqRSu272sHw==', 'Content-Type': 'application/json', 'Content-Length': '3078'}
2023-09-06 01:58:57,726 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 01:58:57,726 INFO    wandb-upload_2:44178 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2491, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2520, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2491, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2023-09-06 01:59:01,592 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/559989766/5366b528953a1441ad7f8f84d022595f?Expires=1694023003&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jl94doxpmR4cIiVtF8CDtpgh9IB95Asn6BqfNG5mTQH8b3bv%2BzNi0dRvsxdQXWq0KUJDDZ4XjYrIg7Lyd1TlyjsVLgNkWg3Av7EOfOiUhDZ0QJ2skvMttt384hWu44E60Siss1yD2238OlnF9GOBOCRaImDehGtih9jsjX68K7%2BgSl9L5UONOzaXCeaqrWvwPTVohuiWE1lTWXGkLR70zzzJtg9cPs3GhHh2vwohWKIB68AZMeziNoEtsEKJBDcX9wflprSC8GO96r67PsKq7JwOPpQl%2BU5hZ6LA2K82Ac8C7KJX8gsfqwt3e7ULv5YURV0j%2FopWuQM3En6fbIhmQA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 01:59:01,592 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 01:59:01,592 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 01:59:10,383 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/559989766/5366b528953a1441ad7f8f84d022595f?Expires=1694023003&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jl94doxpmR4cIiVtF8CDtpgh9IB95Asn6BqfNG5mTQH8b3bv%2BzNi0dRvsxdQXWq0KUJDDZ4XjYrIg7Lyd1TlyjsVLgNkWg3Av7EOfOiUhDZ0QJ2skvMttt384hWu44E60Siss1yD2238OlnF9GOBOCRaImDehGtih9jsjX68K7%2BgSl9L5UONOzaXCeaqrWvwPTVohuiWE1lTWXGkLR70zzzJtg9cPs3GhHh2vwohWKIB68AZMeziNoEtsEKJBDcX9wflprSC8GO96r67PsKq7JwOPpQl%2BU5hZ6LA2K82Ac8C7KJX8gsfqwt3e7ULv5YURV0j%2FopWuQM3En6fbIhmQA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 01:59:10,383 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 01:59:10,383 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 01:59:30,410 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/559989766/5366b528953a1441ad7f8f84d022595f?Expires=1694023003&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jl94doxpmR4cIiVtF8CDtpgh9IB95Asn6BqfNG5mTQH8b3bv%2BzNi0dRvsxdQXWq0KUJDDZ4XjYrIg7Lyd1TlyjsVLgNkWg3Av7EOfOiUhDZ0QJ2skvMttt384hWu44E60Siss1yD2238OlnF9GOBOCRaImDehGtih9jsjX68K7%2BgSl9L5UONOzaXCeaqrWvwPTVohuiWE1lTWXGkLR70zzzJtg9cPs3GhHh2vwohWKIB68AZMeziNoEtsEKJBDcX9wflprSC8GO96r67PsKq7JwOPpQl%2BU5hZ6LA2K82Ac8C7KJX8gsfqwt3e7ULv5YURV0j%2FopWuQM3En6fbIhmQA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 01:59:30,411 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 01:59:30,411 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 02:00:05,396 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/559989766/5366b528953a1441ad7f8f84d022595f?Expires=1694023003&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jl94doxpmR4cIiVtF8CDtpgh9IB95Asn6BqfNG5mTQH8b3bv%2BzNi0dRvsxdQXWq0KUJDDZ4XjYrIg7Lyd1TlyjsVLgNkWg3Av7EOfOiUhDZ0QJ2skvMttt384hWu44E60Siss1yD2238OlnF9GOBOCRaImDehGtih9jsjX68K7%2BgSl9L5UONOzaXCeaqrWvwPTVohuiWE1lTWXGkLR70zzzJtg9cPs3GhHh2vwohWKIB68AZMeziNoEtsEKJBDcX9wflprSC8GO96r67PsKq7JwOPpQl%2BU5hZ6LA2K82Ac8C7KJX8gsfqwt3e7ULv5YURV0j%2FopWuQM3En6fbIhmQA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 02:00:05,396 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 02:00:05,396 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 02:01:10,536 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/559989766/5366b528953a1441ad7f8f84d022595f?Expires=1694023003&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jl94doxpmR4cIiVtF8CDtpgh9IB95Asn6BqfNG5mTQH8b3bv%2BzNi0dRvsxdQXWq0KUJDDZ4XjYrIg7Lyd1TlyjsVLgNkWg3Av7EOfOiUhDZ0QJ2skvMttt384hWu44E60Siss1yD2238OlnF9GOBOCRaImDehGtih9jsjX68K7%2BgSl9L5UONOzaXCeaqrWvwPTVohuiWE1lTWXGkLR70zzzJtg9cPs3GhHh2vwohWKIB68AZMeziNoEtsEKJBDcX9wflprSC8GO96r67PsKq7JwOPpQl%2BU5hZ6LA2K82Ac8C7KJX8gsfqwt3e7ULv5YURV0j%2FopWuQM3En6fbIhmQA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 02:01:10,537 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 02:01:10,537 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 02:01:12,689 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/559989766/a37748b2bbe2fd6ee2a914aedbbdac1f?Expires=1694023003&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IhgEdfFvPG6Y2sW7ocroFiVsqTDHIs%2FmUwXRgsG92Qzn1hROt1hw%2FASznkPBYpOIGZ7vdGxXxbW4JuXGZUVDZza2C6einZaDri9AHi5U32xTTre76yxPZnYiyBAFuq7uFe1AGtarPA3IwN4tMQ%2FYCgdl449t0IarnIq74aCNX9HiRYPyFznho%2Bx%2BEzAjIE%2F8aURKyUDbOyEeqshnyXZTce1cui3Kvb8phroPzC2InFIL2ZZjU9IxtiaZjSSYwgnR9KnkvMjbtyzP1bA4BMyrPvTCqzD%2BraNzjn%2FGJ0ypgAV%2FMR89x0qevmQLF0vpxv2NaGFSk62b2rQJ2VpZFnBGcA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 02:01:12,689 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'o3dIsrvi/W7iqRSu272sHw==', 'Content-Type': 'application/json', 'Content-Length': '3078'}
2023-09-06 02:01:12,689 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 02:01:12,690 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/pe8qai3n/wandb-metadata.json?Expires=1694022995&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=PDKSxivXtSmoKs71EcThGBaVC67GjikFHofxZ4axYYrHY%2BVCrLjXkkNwq%2BdKqvWT1%2BdT%2FPX4%2BMxTnG8gXQr0%2FLQR9abMFQmz08NyR%2BR2xyjn%2FnXAlNAxpl%2FQM2hoZu6odCUb%2BrqWj46MEbbNugmFL%2Bb8PEkaMXPt6A0mWb1cTBYVoBOQUDNAO4T7h%2F07g1kqJFTEBHAQehsadiyjzl2GMim1pdwYASalxqFAk8yr%2FaSTHYEyZ32d%2FCKzu%2FKOC0kHMGDBBQKfaGfut9AKvVLUweivTc2b1JLSNlDZwwK3B77IxrjGeg3HuUCVgC2EJad5osuWtHTHR5eAlmpW1s4Q1A%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 02:01:12,690 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15125'}
2023-09-06 02:01:12,690 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 02:01:30,130 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/pe8qai3n/wandb-metadata.json?Expires=1694022995&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=PDKSxivXtSmoKs71EcThGBaVC67GjikFHofxZ4axYYrHY%2BVCrLjXkkNwq%2BdKqvWT1%2BdT%2FPX4%2BMxTnG8gXQr0%2FLQR9abMFQmz08NyR%2BR2xyjn%2FnXAlNAxpl%2FQM2hoZu6odCUb%2BrqWj46MEbbNugmFL%2Bb8PEkaMXPt6A0mWb1cTBYVoBOQUDNAO4T7h%2F07g1kqJFTEBHAQehsadiyjzl2GMim1pdwYASalxqFAk8yr%2FaSTHYEyZ32d%2FCKzu%2FKOC0kHMGDBBQKfaGfut9AKvVLUweivTc2b1JLSNlDZwwK3B77IxrjGeg3HuUCVgC2EJad5osuWtHTHR5eAlmpW1s4Q1A%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 02:01:30,130 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15125'}
2023-09-06 02:01:30,130 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 02:02:08,457 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/pe8qai3n/wandb-metadata.json?Expires=1694022995&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=PDKSxivXtSmoKs71EcThGBaVC67GjikFHofxZ4axYYrHY%2BVCrLjXkkNwq%2BdKqvWT1%2BdT%2FPX4%2BMxTnG8gXQr0%2FLQR9abMFQmz08NyR%2BR2xyjn%2FnXAlNAxpl%2FQM2hoZu6odCUb%2BrqWj46MEbbNugmFL%2Bb8PEkaMXPt6A0mWb1cTBYVoBOQUDNAO4T7h%2F07g1kqJFTEBHAQehsadiyjzl2GMim1pdwYASalxqFAk8yr%2FaSTHYEyZ32d%2FCKzu%2FKOC0kHMGDBBQKfaGfut9AKvVLUweivTc2b1JLSNlDZwwK3B77IxrjGeg3HuUCVgC2EJad5osuWtHTHR5eAlmpW1s4Q1A%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 02:02:08,457 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15125'}
2023-09-06 02:02:08,457 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 02:03:13,864 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/pe8qai3n/wandb-metadata.json?Expires=1694022995&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=PDKSxivXtSmoKs71EcThGBaVC67GjikFHofxZ4axYYrHY%2BVCrLjXkkNwq%2BdKqvWT1%2BdT%2FPX4%2BMxTnG8gXQr0%2FLQR9abMFQmz08NyR%2BR2xyjn%2FnXAlNAxpl%2FQM2hoZu6odCUb%2BrqWj46MEbbNugmFL%2Bb8PEkaMXPt6A0mWb1cTBYVoBOQUDNAO4T7h%2F07g1kqJFTEBHAQehsadiyjzl2GMim1pdwYASalxqFAk8yr%2FaSTHYEyZ32d%2FCKzu%2FKOC0kHMGDBBQKfaGfut9AKvVLUweivTc2b1JLSNlDZwwK3B77IxrjGeg3HuUCVgC2EJad5osuWtHTHR5eAlmpW1s4Q1A%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 02:03:13,864 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15125'}
2023-09-06 02:03:13,864 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 02:03:26,061 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/559989766/5366b528953a1441ad7f8f84d022595f?Expires=1694023003&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jl94doxpmR4cIiVtF8CDtpgh9IB95Asn6BqfNG5mTQH8b3bv%2BzNi0dRvsxdQXWq0KUJDDZ4XjYrIg7Lyd1TlyjsVLgNkWg3Av7EOfOiUhDZ0QJ2skvMttt384hWu44E60Siss1yD2238OlnF9GOBOCRaImDehGtih9jsjX68K7%2BgSl9L5UONOzaXCeaqrWvwPTVohuiWE1lTWXGkLR70zzzJtg9cPs3GhHh2vwohWKIB68AZMeziNoEtsEKJBDcX9wflprSC8GO96r67PsKq7JwOPpQl%2BU5hZ6LA2K82Ac8C7KJX8gsfqwt3e7ULv5YURV0j%2FopWuQM3En6fbIhmQA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 02:03:26,061 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 02:03:26,061 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 02:03:32,068 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/559989766/a37748b2bbe2fd6ee2a914aedbbdac1f?Expires=1694023003&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IhgEdfFvPG6Y2sW7ocroFiVsqTDHIs%2FmUwXRgsG92Qzn1hROt1hw%2FASznkPBYpOIGZ7vdGxXxbW4JuXGZUVDZza2C6einZaDri9AHi5U32xTTre76yxPZnYiyBAFuq7uFe1AGtarPA3IwN4tMQ%2FYCgdl449t0IarnIq74aCNX9HiRYPyFznho%2Bx%2BEzAjIE%2F8aURKyUDbOyEeqshnyXZTce1cui3Kvb8phroPzC2InFIL2ZZjU9IxtiaZjSSYwgnR9KnkvMjbtyzP1bA4BMyrPvTCqzD%2BraNzjn%2FGJ0ypgAV%2FMR89x0qevmQLF0vpxv2NaGFSk62b2rQJ2VpZFnBGcA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 02:03:32,069 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'o3dIsrvi/W7iqRSu272sHw==', 'Content-Type': 'application/json', 'Content-Length': '3078'}
2023-09-06 02:03:32,069 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 02:05:44,707 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/pe8qai3n/wandb-metadata.json?Expires=1694022995&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=PDKSxivXtSmoKs71EcThGBaVC67GjikFHofxZ4axYYrHY%2BVCrLjXkkNwq%2BdKqvWT1%2BdT%2FPX4%2BMxTnG8gXQr0%2FLQR9abMFQmz08NyR%2BR2xyjn%2FnXAlNAxpl%2FQM2hoZu6odCUb%2BrqWj46MEbbNugmFL%2Bb8PEkaMXPt6A0mWb1cTBYVoBOQUDNAO4T7h%2F07g1kqJFTEBHAQehsadiyjzl2GMim1pdwYASalxqFAk8yr%2FaSTHYEyZ32d%2FCKzu%2FKOC0kHMGDBBQKfaGfut9AKvVLUweivTc2b1JLSNlDZwwK3B77IxrjGeg3HuUCVgC2EJad5osuWtHTHR5eAlmpW1s4Q1A%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 02:05:44,707 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15125'}
2023-09-06 02:05:44,707 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 02:05:59,383 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/559989766/a37748b2bbe2fd6ee2a914aedbbdac1f?Expires=1694023003&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IhgEdfFvPG6Y2sW7ocroFiVsqTDHIs%2FmUwXRgsG92Qzn1hROt1hw%2FASznkPBYpOIGZ7vdGxXxbW4JuXGZUVDZza2C6einZaDri9AHi5U32xTTre76yxPZnYiyBAFuq7uFe1AGtarPA3IwN4tMQ%2FYCgdl449t0IarnIq74aCNX9HiRYPyFznho%2Bx%2BEzAjIE%2F8aURKyUDbOyEeqshnyXZTce1cui3Kvb8phroPzC2InFIL2ZZjU9IxtiaZjSSYwgnR9KnkvMjbtyzP1bA4BMyrPvTCqzD%2BraNzjn%2FGJ0ypgAV%2FMR89x0qevmQLF0vpxv2NaGFSk62b2rQJ2VpZFnBGcA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 02:05:59,383 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'o3dIsrvi/W7iqRSu272sHw==', 'Content-Type': 'application/json', 'Content-Length': '3078'}
2023-09-06 02:05:59,384 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 02:06:33,730 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/559989766/a37748b2bbe2fd6ee2a914aedbbdac1f?Expires=1694023003&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IhgEdfFvPG6Y2sW7ocroFiVsqTDHIs%2FmUwXRgsG92Qzn1hROt1hw%2FASznkPBYpOIGZ7vdGxXxbW4JuXGZUVDZza2C6einZaDri9AHi5U32xTTre76yxPZnYiyBAFuq7uFe1AGtarPA3IwN4tMQ%2FYCgdl449t0IarnIq74aCNX9HiRYPyFznho%2Bx%2BEzAjIE%2F8aURKyUDbOyEeqshnyXZTce1cui3Kvb8phroPzC2InFIL2ZZjU9IxtiaZjSSYwgnR9KnkvMjbtyzP1bA4BMyrPvTCqzD%2BraNzjn%2FGJ0ypgAV%2FMR89x0qevmQLF0vpxv2NaGFSk62b2rQJ2VpZFnBGcA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 02:06:33,730 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'o3dIsrvi/W7iqRSu272sHw==', 'Content-Type': 'application/json', 'Content-Length': '3078'}
2023-09-06 02:06:33,730 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 02:07:52,152 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/559989766/a37748b2bbe2fd6ee2a914aedbbdac1f?Expires=1694023003&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IhgEdfFvPG6Y2sW7ocroFiVsqTDHIs%2FmUwXRgsG92Qzn1hROt1hw%2FASznkPBYpOIGZ7vdGxXxbW4JuXGZUVDZza2C6einZaDri9AHi5U32xTTre76yxPZnYiyBAFuq7uFe1AGtarPA3IwN4tMQ%2FYCgdl449t0IarnIq74aCNX9HiRYPyFznho%2Bx%2BEzAjIE%2F8aURKyUDbOyEeqshnyXZTce1cui3Kvb8phroPzC2InFIL2ZZjU9IxtiaZjSSYwgnR9KnkvMjbtyzP1bA4BMyrPvTCqzD%2BraNzjn%2FGJ0ypgAV%2FMR89x0qevmQLF0vpxv2NaGFSk62b2rQJ2VpZFnBGcA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 02:07:52,152 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'o3dIsrvi/W7iqRSu272sHw==', 'Content-Type': 'application/json', 'Content-Length': '3078'}
2023-09-06 02:07:52,152 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 02:08:07,022 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/559989766/5366b528953a1441ad7f8f84d022595f?Expires=1694023003&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jl94doxpmR4cIiVtF8CDtpgh9IB95Asn6BqfNG5mTQH8b3bv%2BzNi0dRvsxdQXWq0KUJDDZ4XjYrIg7Lyd1TlyjsVLgNkWg3Av7EOfOiUhDZ0QJ2skvMttt384hWu44E60Siss1yD2238OlnF9GOBOCRaImDehGtih9jsjX68K7%2BgSl9L5UONOzaXCeaqrWvwPTVohuiWE1lTWXGkLR70zzzJtg9cPs3GhHh2vwohWKIB68AZMeziNoEtsEKJBDcX9wflprSC8GO96r67PsKq7JwOPpQl%2BU5hZ6LA2K82Ac8C7KJX8gsfqwt3e7ULv5YURV0j%2FopWuQM3En6fbIhmQA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 02:08:07,022 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 02:08:07,022 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 02:10:20,277 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/559989766/a37748b2bbe2fd6ee2a914aedbbdac1f?Expires=1694023003&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IhgEdfFvPG6Y2sW7ocroFiVsqTDHIs%2FmUwXRgsG92Qzn1hROt1hw%2FASznkPBYpOIGZ7vdGxXxbW4JuXGZUVDZza2C6einZaDri9AHi5U32xTTre76yxPZnYiyBAFuq7uFe1AGtarPA3IwN4tMQ%2FYCgdl449t0IarnIq74aCNX9HiRYPyFznho%2Bx%2BEzAjIE%2F8aURKyUDbOyEeqshnyXZTce1cui3Kvb8phroPzC2InFIL2ZZjU9IxtiaZjSSYwgnR9KnkvMjbtyzP1bA4BMyrPvTCqzD%2BraNzjn%2FGJ0ypgAV%2FMR89x0qevmQLF0vpxv2NaGFSk62b2rQJ2VpZFnBGcA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 02:10:20,277 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'o3dIsrvi/W7iqRSu272sHw==', 'Content-Type': 'application/json', 'Content-Length': '3078'}
2023-09-06 02:10:20,278 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 02:10:37,188 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/pe8qai3n/wandb-metadata.json?Expires=1694022995&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=PDKSxivXtSmoKs71EcThGBaVC67GjikFHofxZ4axYYrHY%2BVCrLjXkkNwq%2BdKqvWT1%2BdT%2FPX4%2BMxTnG8gXQr0%2FLQR9abMFQmz08NyR%2BR2xyjn%2FnXAlNAxpl%2FQM2hoZu6odCUb%2BrqWj46MEbbNugmFL%2Bb8PEkaMXPt6A0mWb1cTBYVoBOQUDNAO4T7h%2F07g1kqJFTEBHAQehsadiyjzl2GMim1pdwYASalxqFAk8yr%2FaSTHYEyZ32d%2FCKzu%2FKOC0kHMGDBBQKfaGfut9AKvVLUweivTc2b1JLSNlDZwwK3B77IxrjGeg3HuUCVgC2EJad5osuWtHTHR5eAlmpW1s4Q1A%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 02:10:37,188 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15125'}
2023-09-06 02:10:37,188 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 02:13:15,527 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/559989766/5366b528953a1441ad7f8f84d022595f?Expires=1694023003&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jl94doxpmR4cIiVtF8CDtpgh9IB95Asn6BqfNG5mTQH8b3bv%2BzNi0dRvsxdQXWq0KUJDDZ4XjYrIg7Lyd1TlyjsVLgNkWg3Av7EOfOiUhDZ0QJ2skvMttt384hWu44E60Siss1yD2238OlnF9GOBOCRaImDehGtih9jsjX68K7%2BgSl9L5UONOzaXCeaqrWvwPTVohuiWE1lTWXGkLR70zzzJtg9cPs3GhHh2vwohWKIB68AZMeziNoEtsEKJBDcX9wflprSC8GO96r67PsKq7JwOPpQl%2BU5hZ6LA2K82Ac8C7KJX8gsfqwt3e7ULv5YURV0j%2FopWuQM3En6fbIhmQA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 02:13:15,527 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 02:13:15,527 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 02:16:13,556 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/pe8qai3n/wandb-metadata.json?Expires=1694022995&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=PDKSxivXtSmoKs71EcThGBaVC67GjikFHofxZ4axYYrHY%2BVCrLjXkkNwq%2BdKqvWT1%2BdT%2FPX4%2BMxTnG8gXQr0%2FLQR9abMFQmz08NyR%2BR2xyjn%2FnXAlNAxpl%2FQM2hoZu6odCUb%2BrqWj46MEbbNugmFL%2Bb8PEkaMXPt6A0mWb1cTBYVoBOQUDNAO4T7h%2F07g1kqJFTEBHAQehsadiyjzl2GMim1pdwYASalxqFAk8yr%2FaSTHYEyZ32d%2FCKzu%2FKOC0kHMGDBBQKfaGfut9AKvVLUweivTc2b1JLSNlDZwwK3B77IxrjGeg3HuUCVgC2EJad5osuWtHTHR5eAlmpW1s4Q1A%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 02:16:13,556 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15125'}
2023-09-06 02:16:13,557 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 02:17:25,471 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/559989766/a37748b2bbe2fd6ee2a914aedbbdac1f?Expires=1694023003&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IhgEdfFvPG6Y2sW7ocroFiVsqTDHIs%2FmUwXRgsG92Qzn1hROt1hw%2FASznkPBYpOIGZ7vdGxXxbW4JuXGZUVDZza2C6einZaDri9AHi5U32xTTre76yxPZnYiyBAFuq7uFe1AGtarPA3IwN4tMQ%2FYCgdl449t0IarnIq74aCNX9HiRYPyFznho%2Bx%2BEzAjIE%2F8aURKyUDbOyEeqshnyXZTce1cui3Kvb8phroPzC2InFIL2ZZjU9IxtiaZjSSYwgnR9KnkvMjbtyzP1bA4BMyrPvTCqzD%2BraNzjn%2FGJ0ypgAV%2FMR89x0qevmQLF0vpxv2NaGFSk62b2rQJ2VpZFnBGcA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 02:17:25,471 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'o3dIsrvi/W7iqRSu272sHw==', 'Content-Type': 'application/json', 'Content-Length': '3078'}
2023-09-06 02:17:25,471 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 02:18:22,214 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/559989766/5366b528953a1441ad7f8f84d022595f?Expires=1694023003&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=Jl94doxpmR4cIiVtF8CDtpgh9IB95Asn6BqfNG5mTQH8b3bv%2BzNi0dRvsxdQXWq0KUJDDZ4XjYrIg7Lyd1TlyjsVLgNkWg3Av7EOfOiUhDZ0QJ2skvMttt384hWu44E60Siss1yD2238OlnF9GOBOCRaImDehGtih9jsjX68K7%2BgSl9L5UONOzaXCeaqrWvwPTVohuiWE1lTWXGkLR70zzzJtg9cPs3GhHh2vwohWKIB68AZMeziNoEtsEKJBDcX9wflprSC8GO96r67PsKq7JwOPpQl%2BU5hZ6LA2K82Ac8C7KJX8gsfqwt3e7ULv5YURV0j%2FopWuQM3En6fbIhmQA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 02:18:22,214 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 02:18:22,214 ERROR   wandb-upload_1:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 02:22:06,309 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/pe8qai3n/wandb-metadata.json?Expires=1694022995&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=PDKSxivXtSmoKs71EcThGBaVC67GjikFHofxZ4axYYrHY%2BVCrLjXkkNwq%2BdKqvWT1%2BdT%2FPX4%2BMxTnG8gXQr0%2FLQR9abMFQmz08NyR%2BR2xyjn%2FnXAlNAxpl%2FQM2hoZu6odCUb%2BrqWj46MEbbNugmFL%2Bb8PEkaMXPt6A0mWb1cTBYVoBOQUDNAO4T7h%2F07g1kqJFTEBHAQehsadiyjzl2GMim1pdwYASalxqFAk8yr%2FaSTHYEyZ32d%2FCKzu%2FKOC0kHMGDBBQKfaGfut9AKvVLUweivTc2b1JLSNlDZwwK3B77IxrjGeg3HuUCVgC2EJad5osuWtHTHR5eAlmpW1s4Q1A%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 02:22:06,310 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15125'}
2023-09-06 02:22:06,310 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 02:23:14,806 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/559989766/a37748b2bbe2fd6ee2a914aedbbdac1f?Expires=1694023003&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IhgEdfFvPG6Y2sW7ocroFiVsqTDHIs%2FmUwXRgsG92Qzn1hROt1hw%2FASznkPBYpOIGZ7vdGxXxbW4JuXGZUVDZza2C6einZaDri9AHi5U32xTTre76yxPZnYiyBAFuq7uFe1AGtarPA3IwN4tMQ%2FYCgdl449t0IarnIq74aCNX9HiRYPyFznho%2Bx%2BEzAjIE%2F8aURKyUDbOyEeqshnyXZTce1cui3Kvb8phroPzC2InFIL2ZZjU9IxtiaZjSSYwgnR9KnkvMjbtyzP1bA4BMyrPvTCqzD%2BraNzjn%2FGJ0ypgAV%2FMR89x0qevmQLF0vpxv2NaGFSk62b2rQJ2VpZFnBGcA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 02:23:14,807 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'o3dIsrvi/W7iqRSu272sHw==', 'Content-Type': 'application/json', 'Content-Length': '3078'}
2023-09-06 02:23:14,807 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 02:24:18,681 INFO    wandb-upload_1:44178 [upload_job.py:push():89] Uploaded file /root/.local/share/wandb/artifacts/staging/tmppqx6t719
2023-09-06 02:28:06,109 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/pe8qai3n/wandb-metadata.json?Expires=1694022995&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=PDKSxivXtSmoKs71EcThGBaVC67GjikFHofxZ4axYYrHY%2BVCrLjXkkNwq%2BdKqvWT1%2BdT%2FPX4%2BMxTnG8gXQr0%2FLQR9abMFQmz08NyR%2BR2xyjn%2FnXAlNAxpl%2FQM2hoZu6odCUb%2BrqWj46MEbbNugmFL%2Bb8PEkaMXPt6A0mWb1cTBYVoBOQUDNAO4T7h%2F07g1kqJFTEBHAQehsadiyjzl2GMim1pdwYASalxqFAk8yr%2FaSTHYEyZ32d%2FCKzu%2FKOC0kHMGDBBQKfaGfut9AKvVLUweivTc2b1JLSNlDZwwK3B77IxrjGeg3HuUCVgC2EJad5osuWtHTHR5eAlmpW1s4Q1A%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 02:28:06,109 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15125'}
2023-09-06 02:28:06,110 ERROR   wandb-upload_0:44178 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 02:28:48,296 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/559989766/a37748b2bbe2fd6ee2a914aedbbdac1f?Expires=1694023003&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=IhgEdfFvPG6Y2sW7ocroFiVsqTDHIs%2FmUwXRgsG92Qzn1hROt1hw%2FASznkPBYpOIGZ7vdGxXxbW4JuXGZUVDZza2C6einZaDri9AHi5U32xTTre76yxPZnYiyBAFuq7uFe1AGtarPA3IwN4tMQ%2FYCgdl449t0IarnIq74aCNX9HiRYPyFznho%2Bx%2BEzAjIE%2F8aURKyUDbOyEeqshnyXZTce1cui3Kvb8phroPzC2InFIL2ZZjU9IxtiaZjSSYwgnR9KnkvMjbtyzP1bA4BMyrPvTCqzD%2BraNzjn%2FGJ0ypgAV%2FMR89x0qevmQLF0vpxv2NaGFSk62b2rQJ2VpZFnBGcA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 02:28:48,296 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'o3dIsrvi/W7iqRSu272sHw==', 'Content-Type': 'application/json', 'Content-Length': '3078'}
2023-09-06 02:28:48,296 ERROR   wandb-upload_2:44178 [internal_api.py:upload_file():2500] upload_file response body: 
