2023-09-06 21:46:19,345 INFO    StreamThr :32539 [internal.py:wandb_internal():86] W&B internal server running at pid: 32539, started at: 2023-09-06 21:46:19.343886
2023-09-06 21:46:19,347 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: status
2023-09-06 21:46:19,350 INFO    WriterThread:32539 [datastore.py:open_for_write():85] open: /root/BitFlip/DQNwithHer/outputs/2023-09-06/21-46-16/wandb/run-20230906_214619-77ly5bjx/run-77ly5bjx.wandb
2023-09-06 21:46:19,354 DEBUG   SenderThread:32539 [sender.py:send():379] send: header
2023-09-06 21:46:19,373 DEBUG   SenderThread:32539 [sender.py:send():379] send: run
2023-09-06 21:46:22,751 INFO    SenderThread:32539 [dir_watcher.py:__init__():211] watching files in: /root/BitFlip/DQNwithHer/outputs/2023-09-06/21-46-16/wandb/run-20230906_214619-77ly5bjx/files
2023-09-06 21:46:22,752 INFO    SenderThread:32539 [sender.py:_start_run_threads():1121] run started: 77ly5bjx with start time 1694007979.34287
2023-09-06 21:46:22,761 DEBUG   SenderThread:32539 [sender.py:send_request():406] send_request: summary_record
2023-09-06 21:46:22,761 INFO    SenderThread:32539 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2023-09-06 21:46:22,770 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: check_version
2023-09-06 21:46:22,771 DEBUG   SenderThread:32539 [sender.py:send_request():406] send_request: check_version
2023-09-06 21:46:23,059 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: run_start
2023-09-06 21:46:23,069 DEBUG   HandlerThread:32539 [system_info.py:__init__():31] System info init
2023-09-06 21:46:23,069 DEBUG   HandlerThread:32539 [system_info.py:__init__():46] System info init done
2023-09-06 21:46:23,069 INFO    HandlerThread:32539 [system_monitor.py:start():181] Starting system monitor
2023-09-06 21:46:23,070 INFO    SystemMonitor:32539 [system_monitor.py:_start():145] Starting system asset monitoring threads
2023-09-06 21:46:23,071 INFO    HandlerThread:32539 [system_monitor.py:probe():201] Collecting system info
2023-09-06 21:46:23,074 INFO    SystemMonitor:32539 [interfaces.py:start():190] Started cpu monitoring
2023-09-06 21:46:23,076 INFO    SystemMonitor:32539 [interfaces.py:start():190] Started disk monitoring
2023-09-06 21:46:23,083 INFO    SystemMonitor:32539 [interfaces.py:start():190] Started gpu monitoring
2023-09-06 21:46:23,084 INFO    SystemMonitor:32539 [interfaces.py:start():190] Started memory monitoring
2023-09-06 21:46:23,085 INFO    SystemMonitor:32539 [interfaces.py:start():190] Started network monitoring
2023-09-06 21:46:23,141 DEBUG   HandlerThread:32539 [system_info.py:probe():195] Probing system
2023-09-06 21:46:23,152 DEBUG   HandlerThread:32539 [system_info.py:_probe_git():180] Probing git
2023-09-06 21:46:23,171 DEBUG   HandlerThread:32539 [system_info.py:_probe_git():188] Probing git done
2023-09-06 21:46:23,171 DEBUG   HandlerThread:32539 [system_info.py:probe():240] Probing system done
2023-09-06 21:46:23,172 DEBUG   HandlerThread:32539 [system_monitor.py:probe():210] {'os': 'Linux-5.4.0-132-generic-x86_64-with-glibc2.35', 'python': '3.9.17', 'heartbeatAt': '2023-09-06T13:46:23.141734', 'startedAt': '2023-09-06T13:46:19.338134', 'docker': None, 'cuda': None, 'args': ('length=4', 'epsilon=0.9', 'delta_epsilon=1e-5', 'target_update=50', 'use_wandb=true', 'reward_success=0', 'reward_fail=-1'), 'state': 'running', 'program': '/root/BitFlip/DQNwithHer/main.py', 'codePath': 'DQNwithHer/main.py', 'git': {'remote': 'git@github.com:chjchjchjchjchj/BitFlip.git', 'commit': 'de64834fe3b96021cf8ea4590011ec505c48b8c7'}, 'email': 'chjchjchjchjchj2001@gmail.com', 'root': '/root/BitFlip', 'host': 'autodl-container-b06911993c-7c1fab7a', 'username': 'root', 'executable': '/root/miniconda3/envs/ling/bin/python', 'cpu_count': 64, 'cpu_count_logical': 128, 'cpu_freq': {'current': 1569.3290937499992, 'min': 800.0, 'max': 3500.0}, 'cpu_freq_per_core': [{'current': 1812.313, 'min': 800.0, 'max': 3500.0}, {'current': 2472.721, 'min': 800.0, 'max': 3500.0}, {'current': 1222.855, 'min': 800.0, 'max': 3500.0}, {'current': 2031.728, 'min': 800.0, 'max': 3500.0}, {'current': 2472.549, 'min': 800.0, 'max': 3500.0}, {'current': 887.639, 'min': 800.0, 'max': 3500.0}, {'current': 838.289, 'min': 800.0, 'max': 3500.0}, {'current': 2600.235, 'min': 800.0, 'max': 3500.0}, {'current': 2429.23, 'min': 800.0, 'max': 3500.0}, {'current': 1657.202, 'min': 800.0, 'max': 3500.0}, {'current': 800.0, 'min': 800.0, 'max': 3500.0}, {'current': 1054.643, 'min': 800.0, 'max': 3500.0}, {'current': 2427.335, 'min': 800.0, 'max': 3500.0}, {'current': 2421.779, 'min': 800.0, 'max': 3500.0}, {'current': 904.443, 'min': 800.0, 'max': 3500.0}, {'current': 875.571, 'min': 800.0, 'max': 3500.0}, {'current': 858.623, 'min': 800.0, 'max': 3500.0}, {'current': 953.557, 'min': 800.0, 'max': 3500.0}, {'current': 2519.177, 'min': 800.0, 'max': 3500.0}, {'current': 2458.0, 'min': 800.0, 'max': 3500.0}, {'current': 799.426, 'min': 800.0, 'max': 3500.0}, {'current': 1158.407, 'min': 800.0, 'max': 3500.0}, {'current': 1235.355, 'min': 800.0, 'max': 3500.0}, {'current': 918.283, 'min': 800.0, 'max': 3500.0}, {'current': 2292.608, 'min': 800.0, 'max': 3500.0}, {'current': 1101.754, 'min': 800.0, 'max': 3500.0}, {'current': 891.039, 'min': 800.0, 'max': 3500.0}, {'current': 1128.259, 'min': 800.0, 'max': 3500.0}, {'current': 1689.018, 'min': 800.0, 'max': 3500.0}, {'current': 2448.581, 'min': 800.0, 'max': 3500.0}, {'current': 801.304, 'min': 800.0, 'max': 3500.0}, {'current': 980.571, 'min': 800.0, 'max': 3500.0}, {'current': 1913.994, 'min': 800.0, 'max': 3500.0}, {'current': 1060.081, 'min': 800.0, 'max': 3500.0}, {'current': 2328.991, 'min': 800.0, 'max': 3500.0}, {'current': 1600.0, 'min': 800.0, 'max': 3500.0}, {'current': 1128.947, 'min': 800.0, 'max': 3500.0}, {'current': 2271.485, 'min': 800.0, 'max': 3500.0}, {'current': 2971.453, 'min': 800.0, 'max': 3500.0}, {'current': 801.006, 'min': 800.0, 'max': 3500.0}, {'current': 1597.979, 'min': 800.0, 'max': 3500.0}, {'current': 826.658, 'min': 800.0, 'max': 3500.0}, {'current': 1179.233, 'min': 800.0, 'max': 3500.0}, {'current': 1151.835, 'min': 800.0, 'max': 3500.0}, {'current': 1098.122, 'min': 800.0, 'max': 3500.0}, {'current': 1848.031, 'min': 800.0, 'max': 3500.0}, {'current': 801.008, 'min': 800.0, 'max': 3500.0}, {'current': 894.707, 'min': 800.0, 'max': 3500.0}, {'current': 2600.0, 'min': 800.0, 'max': 3500.0}, {'current': 800.0, 'min': 800.0, 'max': 3500.0}, {'current': 1106.152, 'min': 800.0, 'max': 3500.0}, {'current': 1738.436, 'min': 800.0, 'max': 3500.0}, {'current': 1145.882, 'min': 800.0, 'max': 3500.0}, {'current': 938.134, 'min': 800.0, 'max': 3500.0}, {'current': 800.0, 'min': 800.0, 'max': 3500.0}, {'current': 799.274, 'min': 800.0, 'max': 3500.0}, {'current': 800.559, 'min': 800.0, 'max': 3500.0}, {'current': 1600.0, 'min': 800.0, 'max': 3500.0}, {'current': 1627.912, 'min': 800.0, 'max': 3500.0}, {'current': 917.223, 'min': 800.0, 'max': 3500.0}, {'current': 800.0, 'min': 800.0, 'max': 3500.0}, {'current': 1398.197, 'min': 800.0, 'max': 3500.0}, {'current': 800.727, 'min': 800.0, 'max': 3500.0}, {'current': 2596.692, 'min': 800.0, 'max': 3500.0}, {'current': 986.547, 'min': 800.0, 'max': 3500.0}, {'current': 2594.167, 'min': 800.0, 'max': 3500.0}, {'current': 1911.188, 'min': 800.0, 'max': 3500.0}, {'current': 1909.425, 'min': 800.0, 'max': 3500.0}, {'current': 2421.0, 'min': 800.0, 'max': 3500.0}, {'current': 879.536, 'min': 800.0, 'max': 3500.0}, {'current': 808.868, 'min': 800.0, 'max': 3500.0}, {'current': 2600.0, 'min': 800.0, 'max': 3500.0}, {'current': 2599.997, 'min': 800.0, 'max': 3500.0}, {'current': 2549.294, 'min': 800.0, 'max': 3500.0}, {'current': 800.278, 'min': 800.0, 'max': 3500.0}, {'current': 1090.397, 'min': 800.0, 'max': 3500.0}, {'current': 1521.841, 'min': 800.0, 'max': 3500.0}, {'current': 2319.995, 'min': 800.0, 'max': 3500.0}, {'current': 813.165, 'min': 800.0, 'max': 3500.0}, {'current': 873.703, 'min': 800.0, 'max': 3500.0}, {'current': 829.349, 'min': 800.0, 'max': 3500.0}, {'current': 955.268, 'min': 800.0, 'max': 3500.0}, {'current': 2399.282, 'min': 800.0, 'max': 3500.0}, {'current': 2433.281, 'min': 800.0, 'max': 3500.0}, {'current': 1014.052, 'min': 800.0, 'max': 3500.0}, {'current': 2588.07, 'min': 800.0, 'max': 3500.0}, {'current': 2597.275, 'min': 800.0, 'max': 3500.0}, {'current': 801.333, 'min': 800.0, 'max': 3500.0}, {'current': 2216.103, 'min': 800.0, 'max': 3500.0}, {'current': 2548.867, 'min': 800.0, 'max': 3500.0}, {'current': 830.915, 'min': 800.0, 'max': 3500.0}, {'current': 2556.491, 'min': 800.0, 'max': 3500.0}, {'current': 2595.956, 'min': 800.0, 'max': 3500.0}, {'current': 2416.053, 'min': 800.0, 'max': 3500.0}, {'current': 800.89, 'min': 800.0, 'max': 3500.0}, {'current': 887.094, 'min': 800.0, 'max': 3500.0}, {'current': 2148.334, 'min': 800.0, 'max': 3500.0}, {'current': 1244.293, 'min': 800.0, 'max': 3500.0}, {'current': 1852.356, 'min': 800.0, 'max': 3500.0}, {'current': 1619.626, 'min': 800.0, 'max': 3500.0}, {'current': 1739.052, 'min': 800.0, 'max': 3500.0}, {'current': 2262.701, 'min': 800.0, 'max': 3500.0}, {'current': 3155.782, 'min': 800.0, 'max': 3500.0}, {'current': 1327.587, 'min': 800.0, 'max': 3500.0}, {'current': 1632.452, 'min': 800.0, 'max': 3500.0}, {'current': 1276.813, 'min': 800.0, 'max': 3500.0}, {'current': 1313.249, 'min': 800.0, 'max': 3500.0}, {'current': 1596.784, 'min': 800.0, 'max': 3500.0}, {'current': 1100.228, 'min': 800.0, 'max': 3500.0}, {'current': 1618.404, 'min': 800.0, 'max': 3500.0}, {'current': 1169.823, 'min': 800.0, 'max': 3500.0}, {'current': 897.977, 'min': 800.0, 'max': 3500.0}, {'current': 2599.998, 'min': 800.0, 'max': 3500.0}, {'current': 800.662, 'min': 800.0, 'max': 3500.0}, {'current': 1153.333, 'min': 800.0, 'max': 3500.0}, {'current': 1740.519, 'min': 800.0, 'max': 3500.0}, {'current': 809.838, 'min': 800.0, 'max': 3500.0}, {'current': 1612.466, 'min': 800.0, 'max': 3500.0}, {'current': 799.892, 'min': 800.0, 'max': 3500.0}, {'current': 909.044, 'min': 800.0, 'max': 3500.0}, {'current': 1589.64, 'min': 800.0, 'max': 3500.0}, {'current': 1620.729, 'min': 800.0, 'max': 3500.0}, {'current': 1462.675, 'min': 800.0, 'max': 3500.0}, {'current': 1373.119, 'min': 800.0, 'max': 3500.0}, {'current': 799.962, 'min': 800.0, 'max': 3500.0}, {'current': 1401.734, 'min': 800.0, 'max': 3500.0}, {'current': 800.95, 'min': 800.0, 'max': 3500.0}, {'current': 2422.521, 'min': 800.0, 'max': 3500.0}], 'disk': {'total': 30.0, 'used': 11.402053833007812}, 'gpu': 'NVIDIA GeForce RTX 3090', 'gpu_count': 4, 'gpu_devices': [{'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}, {'name': 'NVIDIA GeForce RTX 3090', 'memory_total': 25769803776}], 'memory': {'total': 377.53807830810547}}
2023-09-06 21:46:23,172 INFO    HandlerThread:32539 [system_monitor.py:probe():211] Finished collecting system info
2023-09-06 21:46:23,172 INFO    HandlerThread:32539 [system_monitor.py:probe():214] Publishing system info
2023-09-06 21:46:23,172 DEBUG   HandlerThread:32539 [system_info.py:_save_pip():51] Saving list of pip packages installed into the current environment
2023-09-06 21:46:23,172 DEBUG   HandlerThread:32539 [system_info.py:_save_pip():67] Saving pip packages done
2023-09-06 21:46:23,173 DEBUG   HandlerThread:32539 [system_info.py:_save_conda():74] Saving list of conda packages installed into the current environment
2023-09-06 21:46:23,177 ERROR   HandlerThread:32539 [system_info.py:_save_conda():85] Error saving conda packages: [Errno 2] No such file or directory: 'conda'
Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/system/system_info.py", line 81, in _save_conda
    subprocess.call(
  File "/root/miniconda3/envs/ling/lib/python3.9/subprocess.py", line 349, in call
    with Popen(*popenargs, **kwargs) as p:
  File "/root/miniconda3/envs/ling/lib/python3.9/subprocess.py", line 951, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/root/miniconda3/envs/ling/lib/python3.9/subprocess.py", line 1837, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'conda'
2023-09-06 21:46:23,178 DEBUG   HandlerThread:32539 [system_info.py:_save_conda():86] Saving conda packages done
2023-09-06 21:46:23,180 INFO    HandlerThread:32539 [system_monitor.py:probe():216] Finished publishing system info
2023-09-06 21:46:23,188 DEBUG   SenderThread:32539 [sender.py:send():379] send: files
2023-09-06 21:46:23,189 INFO    SenderThread:32539 [sender.py:_save_file():1375] saving file wandb-metadata.json with policy now
2023-09-06 21:46:23,198 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: stop_status
2023-09-06 21:46:23,199 DEBUG   SenderThread:32539 [sender.py:send_request():406] send_request: stop_status
2023-09-06 21:46:23,763 INFO    Thread-12 :32539 [dir_watcher.py:_on_file_created():271] file/dir created: /root/BitFlip/DQNwithHer/outputs/2023-09-06/21-46-16/wandb/run-20230906_214619-77ly5bjx/files/wandb-metadata.json
2023-09-06 21:46:23,764 INFO    Thread-12 :32539 [dir_watcher.py:_on_file_created():271] file/dir created: /root/BitFlip/DQNwithHer/outputs/2023-09-06/21-46-16/wandb/run-20230906_214619-77ly5bjx/files/requirements.txt
2023-09-06 21:46:23,764 INFO    Thread-12 :32539 [dir_watcher.py:_on_file_created():271] file/dir created: /root/BitFlip/DQNwithHer/outputs/2023-09-06/21-46-16/wandb/run-20230906_214619-77ly5bjx/files/wandb-summary.json
2023-09-06 21:46:23,764 INFO    Thread-12 :32539 [dir_watcher.py:_on_file_created():271] file/dir created: /root/BitFlip/DQNwithHer/outputs/2023-09-06/21-46-16/wandb/run-20230906_214619-77ly5bjx/files/conda-environment.yaml
2023-09-06 21:46:24,200 DEBUG   SenderThread:32539 [sender.py:send():379] send: telemetry
2023-09-06 21:46:24,545 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: status_report
2023-09-06 21:46:24,545 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: partial_history
2023-09-06 21:46:24,549 DEBUG   SenderThread:32539 [sender.py:send():379] send: history
2023-09-06 21:46:24,550 DEBUG   SenderThread:32539 [sender.py:send_request():406] send_request: summary_record
2023-09-06 21:46:24,551 INFO    SenderThread:32539 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2023-09-06 21:46:24,564 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/77ly5bjx/wandb-metadata.json?Expires=1694094384&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=R8n5MHAlhJmORTpb%2Fcc3RjjPSKvKbC9XsS6LnVsZdl1zAcI0%2B5cqcsL%2FLqIdlMTUarwnye25myYt7qdRE0MghvoEDGGGnY%2FgeecORooJHzY4eTrL%2BkRFm3LCa3j%2BTgFgPRTxUWhKr1Y4ZUwml5Oy3d1a6CjcPDVdOxOnHULkmFzbDa7r36BNHyFKJLZ%2BLu1aLZvYifXbfrz%2B1%2Bf%2F27N6AFtJeYAAwNKhGH9mKsUHXP%2Byu3C5w5As37VDiT%2FTk8YxaRZVWt18FYaWpJzLswvT%2F0iCudfv52tIdFNj8aIAPkatWM0TBsdjdhFcKeDrOUhowlRNG%2B4rpj3G3%2Bl22l05lQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:46:24,565 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15236'}
2023-09-06 21:46:24,565 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:46:24,754 INFO    Thread-12 :32539 [dir_watcher.py:_on_file_modified():288] file/dir modified: /root/BitFlip/DQNwithHer/outputs/2023-09-06/21-46-16/wandb/run-20230906_214619-77ly5bjx/files/wandb-summary.json
2023-09-06 21:46:24,755 INFO    Thread-12 :32539 [dir_watcher.py:_on_file_created():271] file/dir created: /root/BitFlip/DQNwithHer/outputs/2023-09-06/21-46-16/wandb/run-20230906_214619-77ly5bjx/files/output.log
2023-09-06 21:46:26,756 INFO    Thread-12 :32539 [dir_watcher.py:_on_file_modified():288] file/dir modified: /root/BitFlip/DQNwithHer/outputs/2023-09-06/21-46-16/wandb/run-20230906_214619-77ly5bjx/files/output.log
2023-09-06 21:46:28,221 DEBUG   SenderThread:32539 [sender.py:send():379] send: exit
2023-09-06 21:46:28,221 INFO    SenderThread:32539 [sender.py:send_exit():584] handling exit code: 255
2023-09-06 21:46:28,222 INFO    SenderThread:32539 [sender.py:send_exit():586] handling runtime: 5
2023-09-06 21:46:28,223 INFO    SenderThread:32539 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2023-09-06 21:46:28,223 INFO    SenderThread:32539 [sender.py:send_exit():592] send defer
2023-09-06 21:46:28,223 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: defer
2023-09-06 21:46:28,224 INFO    HandlerThread:32539 [handler.py:handle_request_defer():170] handle defer: 0
2023-09-06 21:46:28,224 DEBUG   SenderThread:32539 [sender.py:send_request():406] send_request: defer
2023-09-06 21:46:28,224 INFO    SenderThread:32539 [sender.py:send_request_defer():608] handle sender defer: 0
2023-09-06 21:46:28,224 INFO    SenderThread:32539 [sender.py:transition_state():612] send defer: 1
2023-09-06 21:46:28,225 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: defer
2023-09-06 21:46:28,225 INFO    HandlerThread:32539 [handler.py:handle_request_defer():170] handle defer: 1
2023-09-06 21:46:28,225 DEBUG   SenderThread:32539 [sender.py:send_request():406] send_request: defer
2023-09-06 21:46:28,225 INFO    SenderThread:32539 [sender.py:send_request_defer():608] handle sender defer: 1
2023-09-06 21:46:28,226 INFO    SenderThread:32539 [sender.py:transition_state():612] send defer: 2
2023-09-06 21:46:28,226 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: defer
2023-09-06 21:46:28,226 INFO    HandlerThread:32539 [handler.py:handle_request_defer():170] handle defer: 2
2023-09-06 21:46:28,226 INFO    HandlerThread:32539 [system_monitor.py:finish():190] Stopping system monitor
2023-09-06 21:46:28,226 DEBUG   SystemMonitor:32539 [system_monitor.py:_start():159] Starting system metrics aggregation loop
2023-09-06 21:46:28,228 INFO    HandlerThread:32539 [interfaces.py:finish():202] Joined cpu monitor
2023-09-06 21:46:28,228 DEBUG   SystemMonitor:32539 [system_monitor.py:_start():166] Finished system metrics aggregation loop
2023-09-06 21:46:28,228 INFO    HandlerThread:32539 [interfaces.py:finish():202] Joined disk monitor
2023-09-06 21:46:28,229 DEBUG   SystemMonitor:32539 [system_monitor.py:_start():170] Publishing last batch of metrics
2023-09-06 21:46:28,297 INFO    HandlerThread:32539 [interfaces.py:finish():202] Joined gpu monitor
2023-09-06 21:46:28,298 INFO    HandlerThread:32539 [interfaces.py:finish():202] Joined memory monitor
2023-09-06 21:46:28,298 INFO    HandlerThread:32539 [interfaces.py:finish():202] Joined network monitor
2023-09-06 21:46:28,299 DEBUG   SenderThread:32539 [sender.py:send_request():406] send_request: defer
2023-09-06 21:46:28,300 INFO    SenderThread:32539 [sender.py:send_request_defer():608] handle sender defer: 2
2023-09-06 21:46:28,300 INFO    SenderThread:32539 [sender.py:transition_state():612] send defer: 3
2023-09-06 21:46:28,300 DEBUG   SenderThread:32539 [sender.py:send():379] send: stats
2023-09-06 21:46:28,301 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: defer
2023-09-06 21:46:28,303 INFO    HandlerThread:32539 [handler.py:handle_request_defer():170] handle defer: 3
2023-09-06 21:46:28,304 DEBUG   SenderThread:32539 [sender.py:send_request():406] send_request: defer
2023-09-06 21:46:28,304 INFO    SenderThread:32539 [sender.py:send_request_defer():608] handle sender defer: 3
2023-09-06 21:46:28,304 INFO    SenderThread:32539 [sender.py:transition_state():612] send defer: 4
2023-09-06 21:46:28,304 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: defer
2023-09-06 21:46:28,304 INFO    HandlerThread:32539 [handler.py:handle_request_defer():170] handle defer: 4
2023-09-06 21:46:28,305 DEBUG   SenderThread:32539 [sender.py:send_request():406] send_request: defer
2023-09-06 21:46:28,305 INFO    SenderThread:32539 [sender.py:send_request_defer():608] handle sender defer: 4
2023-09-06 21:46:28,305 INFO    SenderThread:32539 [sender.py:transition_state():612] send defer: 5
2023-09-06 21:46:28,305 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: defer
2023-09-06 21:46:28,305 INFO    HandlerThread:32539 [handler.py:handle_request_defer():170] handle defer: 5
2023-09-06 21:46:28,306 DEBUG   SenderThread:32539 [sender.py:send():379] send: summary
2023-09-06 21:46:28,307 INFO    SenderThread:32539 [sender.py:_save_file():1375] saving file wandb-summary.json with policy end
2023-09-06 21:46:28,307 DEBUG   SenderThread:32539 [sender.py:send_request():406] send_request: defer
2023-09-06 21:46:28,307 INFO    SenderThread:32539 [sender.py:send_request_defer():608] handle sender defer: 5
2023-09-06 21:46:28,308 INFO    SenderThread:32539 [sender.py:transition_state():612] send defer: 6
2023-09-06 21:46:28,308 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: defer
2023-09-06 21:46:28,308 INFO    HandlerThread:32539 [handler.py:handle_request_defer():170] handle defer: 6
2023-09-06 21:46:28,308 DEBUG   SenderThread:32539 [sender.py:send_request():406] send_request: defer
2023-09-06 21:46:28,308 INFO    SenderThread:32539 [sender.py:send_request_defer():608] handle sender defer: 6
2023-09-06 21:46:28,313 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: status_report
2023-09-06 21:46:28,757 INFO    Thread-12 :32539 [dir_watcher.py:_on_file_modified():288] file/dir modified: /root/BitFlip/DQNwithHer/outputs/2023-09-06/21-46-16/wandb/run-20230906_214619-77ly5bjx/files/output.log
2023-09-06 21:46:28,757 INFO    Thread-12 :32539 [dir_watcher.py:_on_file_modified():288] file/dir modified: /root/BitFlip/DQNwithHer/outputs/2023-09-06/21-46-16/wandb/run-20230906_214619-77ly5bjx/files/wandb-summary.json
2023-09-06 21:46:29,215 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: poll_exit
2023-09-06 21:46:29,522 INFO    SenderThread:32539 [sender.py:transition_state():612] send defer: 7
2023-09-06 21:46:29,523 DEBUG   SenderThread:32539 [sender.py:send_request():406] send_request: poll_exit
2023-09-06 21:46:29,523 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: defer
2023-09-06 21:46:29,524 INFO    HandlerThread:32539 [handler.py:handle_request_defer():170] handle defer: 7
2023-09-06 21:46:29,525 DEBUG   SenderThread:32539 [sender.py:send_request():406] send_request: defer
2023-09-06 21:46:29,525 INFO    SenderThread:32539 [sender.py:send_request_defer():608] handle sender defer: 7
2023-09-06 21:46:29,757 INFO    Thread-12 :32539 [dir_watcher.py:_on_file_modified():288] file/dir modified: /root/BitFlip/DQNwithHer/outputs/2023-09-06/21-46-16/wandb/run-20230906_214619-77ly5bjx/files/config.yaml
2023-09-06 21:46:30,216 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: poll_exit
2023-09-06 21:46:30,557 INFO    SenderThread:32539 [sender.py:transition_state():612] send defer: 8
2023-09-06 21:46:30,558 DEBUG   SenderThread:32539 [sender.py:send_request():406] send_request: poll_exit
2023-09-06 21:46:30,558 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: defer
2023-09-06 21:46:30,559 INFO    HandlerThread:32539 [handler.py:handle_request_defer():170] handle defer: 8
2023-09-06 21:46:30,559 DEBUG   SenderThread:32539 [sender.py:send_request():406] send_request: defer
2023-09-06 21:46:30,559 INFO    SenderThread:32539 [sender.py:send_request_defer():608] handle sender defer: 8
2023-09-06 21:46:30,559 INFO    SenderThread:32539 [job_builder.py:build():281] Attempting to build job artifact
2023-09-06 21:46:30,561 INFO    SenderThread:32539 [job_builder.py:_get_source_type():400] is repo sourced job
2023-09-06 21:46:30,565 INFO    SenderThread:32539 [job_builder.py:build():374] adding wandb-job metadata file
2023-09-06 21:46:30,569 INFO    SenderThread:32539 [sender.py:transition_state():612] send defer: 9
2023-09-06 21:46:30,570 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: defer
2023-09-06 21:46:30,570 DEBUG   SenderThread:32539 [sender.py:send():379] send: artifact
2023-09-06 21:46:30,570 INFO    HandlerThread:32539 [handler.py:handle_request_defer():170] handle defer: 9
2023-09-06 21:46:30,758 INFO    Thread-12 :32539 [dir_watcher.py:_on_file_modified():288] file/dir modified: /root/BitFlip/DQNwithHer/outputs/2023-09-06/21-46-16/wandb/run-20230906_214619-77ly5bjx/files/output.log
2023-09-06 21:46:31,217 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: poll_exit
2023-09-06 21:46:34,593 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/5366b528953a1441ad7f8f84d022595f?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ny2qAF1qTjoHyLPSUQZnpPzfzTwH3AbEtAaCABjB4PV0ayR57v2eg9bvhifVv7VW%2FrdPJ7x%2FNjgo92oFxy48UVCYnZ1NNjFlHbneTFOQUMavHm0A%2FsHcO02w7%2Bsej7WRZxOcLv%2FLE3TqUuzlc0%2BhlOkXyzmrxKDtF4OZ3gYsqHzBq2wbc%2FSjT%2B4OY3gjl54eEdw5SgoZwKpS%2BZVvQNwiBjTALEsByePJRXQM47mDiJpzFCJRdIWASKe%2BYQYfUeSNdJ3qela%2B9XAA6hFNLb9pITMQGRkMjaGc6blyNmDHpFmMjrbywQR%2FLJ4Uty6Z0GfJq1pK24vhDlKjjkWbxY2C1g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:46:34,593 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 21:46:34,593 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:46:34,741 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/47012f79cc6a2c5629c47753decaa244?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wrdfadiHmjHjZrn7Uwr3uy75v2I71xdAJRqjFgIplYXWnuVB94sFNF3YTv713xcR8cU92Lbrj2vlhSXg4pdJMlNyl7KlNphkfV%2Ft%2F6kzVO6E7gxBO%2BZDRRZt3iO8r47ECyTqDz%2F3IaZCnD4EuKuR9qB3leNaCo6fGsjpF7LaeWBYkLB6TjXrbooW0q1xwmozY%2Fywv6%2FD3NmpqJHGpGbz53n5JZmkRoGOKVB4L13uJ1kqmhANce8PWJMdKw7GlVgZBMKgQEylZE%2FSpSrUGI3sjwoD3jvuDWeDQpzzvdK0AGRKgi2GLGPgzo25lDkKT%2BNjFWcc6ANLTB9QOLKFF8ZvhA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:46:34,741 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'RwEvecxqLFYpxHdT3sqiRA==', 'Content-Type': 'application/json', 'Content-Length': '3359'}
2023-09-06 21:46:34,741 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:46:36,116 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/47012f79cc6a2c5629c47753decaa244?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wrdfadiHmjHjZrn7Uwr3uy75v2I71xdAJRqjFgIplYXWnuVB94sFNF3YTv713xcR8cU92Lbrj2vlhSXg4pdJMlNyl7KlNphkfV%2Ft%2F6kzVO6E7gxBO%2BZDRRZt3iO8r47ECyTqDz%2F3IaZCnD4EuKuR9qB3leNaCo6fGsjpF7LaeWBYkLB6TjXrbooW0q1xwmozY%2Fywv6%2FD3NmpqJHGpGbz53n5JZmkRoGOKVB4L13uJ1kqmhANce8PWJMdKw7GlVgZBMKgQEylZE%2FSpSrUGI3sjwoD3jvuDWeDQpzzvdK0AGRKgi2GLGPgzo25lDkKT%2BNjFWcc6ANLTB9QOLKFF8ZvhA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:46:36,116 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'RwEvecxqLFYpxHdT3sqiRA==', 'Content-Type': 'application/json', 'Content-Length': '3359'}
2023-09-06 21:46:36,117 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:46:36,220 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: keepalive
2023-09-06 21:46:41,223 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: keepalive
2023-09-06 21:46:46,226 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: keepalive
2023-09-06 21:46:51,228 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: keepalive
2023-09-06 21:46:56,232 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: keepalive
2023-09-06 21:47:01,234 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: keepalive
2023-09-06 21:47:06,237 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: keepalive
2023-09-06 21:47:11,240 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: keepalive
2023-09-06 21:47:16,244 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: keepalive
2023-09-06 21:47:21,246 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: keepalive
2023-09-06 21:47:26,249 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: keepalive
2023-09-06 21:47:31,252 DEBUG   HandlerThread:32539 [handler.py:handle_request():144] handle_request: keepalive
2023-09-06 21:47:32,422 WARNING StreamThr :32539 [internal.py:is_dead():414] Internal process exiting, parent pid 32495 disappeared
2023-09-06 21:47:32,422 ERROR   StreamThr :32539 [internal.py:wandb_internal():152] Internal process shutdown.
2023-09-06 21:47:33,230 INFO    WriterThread:32539 [datastore.py:close():294] close: /root/BitFlip/DQNwithHer/outputs/2023-09-06/21-46-16/wandb/run-20230906_214619-77ly5bjx/run-77ly5bjx.wandb
2023-09-06 21:47:33,253 INFO    HandlerThread:32539 [handler.py:finish():861] shutting down handler
2023-09-06 21:48:36,574 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/77ly5bjx/wandb-metadata.json?Expires=1694094384&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=R8n5MHAlhJmORTpb%2Fcc3RjjPSKvKbC9XsS6LnVsZdl1zAcI0%2B5cqcsL%2FLqIdlMTUarwnye25myYt7qdRE0MghvoEDGGGnY%2FgeecORooJHzY4eTrL%2BkRFm3LCa3j%2BTgFgPRTxUWhKr1Y4ZUwml5Oy3d1a6CjcPDVdOxOnHULkmFzbDa7r36BNHyFKJLZ%2BLu1aLZvYifXbfrz%2B1%2Bf%2F27N6AFtJeYAAwNKhGH9mKsUHXP%2Byu3C5w5As37VDiT%2FTk8YxaRZVWt18FYaWpJzLswvT%2F0iCudfv52tIdFNj8aIAPkatWM0TBsdjdhFcKeDrOUhowlRNG%2B4rpj3G3%2Bl22l05lQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:48:36,575 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15236'}
2023-09-06 21:48:36,575 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:48:46,821 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/5366b528953a1441ad7f8f84d022595f?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ny2qAF1qTjoHyLPSUQZnpPzfzTwH3AbEtAaCABjB4PV0ayR57v2eg9bvhifVv7VW%2FrdPJ7x%2FNjgo92oFxy48UVCYnZ1NNjFlHbneTFOQUMavHm0A%2FsHcO02w7%2Bsej7WRZxOcLv%2FLE3TqUuzlc0%2BhlOkXyzmrxKDtF4OZ3gYsqHzBq2wbc%2FSjT%2B4OY3gjl54eEdw5SgoZwKpS%2BZVvQNwiBjTALEsByePJRXQM47mDiJpzFCJRdIWASKe%2BYQYfUeSNdJ3qela%2B9XAA6hFNLb9pITMQGRkMjaGc6blyNmDHpFmMjrbywQR%2FLJ4Uty6Z0GfJq1pK24vhDlKjjkWbxY2C1g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:48:46,821 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 21:48:46,822 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:48:48,720 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/47012f79cc6a2c5629c47753decaa244?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wrdfadiHmjHjZrn7Uwr3uy75v2I71xdAJRqjFgIplYXWnuVB94sFNF3YTv713xcR8cU92Lbrj2vlhSXg4pdJMlNyl7KlNphkfV%2Ft%2F6kzVO6E7gxBO%2BZDRRZt3iO8r47ECyTqDz%2F3IaZCnD4EuKuR9qB3leNaCo6fGsjpF7LaeWBYkLB6TjXrbooW0q1xwmozY%2Fywv6%2FD3NmpqJHGpGbz53n5JZmkRoGOKVB4L13uJ1kqmhANce8PWJMdKw7GlVgZBMKgQEylZE%2FSpSrUGI3sjwoD3jvuDWeDQpzzvdK0AGRKgi2GLGPgzo25lDkKT%2BNjFWcc6ANLTB9QOLKFF8ZvhA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:48:48,720 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'RwEvecxqLFYpxHdT3sqiRA==', 'Content-Type': 'application/json', 'Content-Length': '3359'}
2023-09-06 21:48:48,720 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:48:48,720 INFO    wandb-upload_2:32539 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2491, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2520, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2491, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2023-09-06 21:48:49,172 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/5366b528953a1441ad7f8f84d022595f?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ny2qAF1qTjoHyLPSUQZnpPzfzTwH3AbEtAaCABjB4PV0ayR57v2eg9bvhifVv7VW%2FrdPJ7x%2FNjgo92oFxy48UVCYnZ1NNjFlHbneTFOQUMavHm0A%2FsHcO02w7%2Bsej7WRZxOcLv%2FLE3TqUuzlc0%2BhlOkXyzmrxKDtF4OZ3gYsqHzBq2wbc%2FSjT%2B4OY3gjl54eEdw5SgoZwKpS%2BZVvQNwiBjTALEsByePJRXQM47mDiJpzFCJRdIWASKe%2BYQYfUeSNdJ3qela%2B9XAA6hFNLb9pITMQGRkMjaGc6blyNmDHpFmMjrbywQR%2FLJ4Uty6Z0GfJq1pK24vhDlKjjkWbxY2C1g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:48:49,172 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 21:48:49,172 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:48:49,172 INFO    wandb-upload_1:32539 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2491, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2520, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2491, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2023-09-06 21:48:53,629 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/47012f79cc6a2c5629c47753decaa244?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wrdfadiHmjHjZrn7Uwr3uy75v2I71xdAJRqjFgIplYXWnuVB94sFNF3YTv713xcR8cU92Lbrj2vlhSXg4pdJMlNyl7KlNphkfV%2Ft%2F6kzVO6E7gxBO%2BZDRRZt3iO8r47ECyTqDz%2F3IaZCnD4EuKuR9qB3leNaCo6fGsjpF7LaeWBYkLB6TjXrbooW0q1xwmozY%2Fywv6%2FD3NmpqJHGpGbz53n5JZmkRoGOKVB4L13uJ1kqmhANce8PWJMdKw7GlVgZBMKgQEylZE%2FSpSrUGI3sjwoD3jvuDWeDQpzzvdK0AGRKgi2GLGPgzo25lDkKT%2BNjFWcc6ANLTB9QOLKFF8ZvhA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:48:53,629 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'RwEvecxqLFYpxHdT3sqiRA==', 'Content-Type': 'application/json', 'Content-Length': '3359'}
2023-09-06 21:48:53,629 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:49:02,530 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/47012f79cc6a2c5629c47753decaa244?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wrdfadiHmjHjZrn7Uwr3uy75v2I71xdAJRqjFgIplYXWnuVB94sFNF3YTv713xcR8cU92Lbrj2vlhSXg4pdJMlNyl7KlNphkfV%2Ft%2F6kzVO6E7gxBO%2BZDRRZt3iO8r47ECyTqDz%2F3IaZCnD4EuKuR9qB3leNaCo6fGsjpF7LaeWBYkLB6TjXrbooW0q1xwmozY%2Fywv6%2FD3NmpqJHGpGbz53n5JZmkRoGOKVB4L13uJ1kqmhANce8PWJMdKw7GlVgZBMKgQEylZE%2FSpSrUGI3sjwoD3jvuDWeDQpzzvdK0AGRKgi2GLGPgzo25lDkKT%2BNjFWcc6ANLTB9QOLKFF8ZvhA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:49:02,531 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'RwEvecxqLFYpxHdT3sqiRA==', 'Content-Type': 'application/json', 'Content-Length': '3359'}
2023-09-06 21:49:02,531 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:49:19,785 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/47012f79cc6a2c5629c47753decaa244?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wrdfadiHmjHjZrn7Uwr3uy75v2I71xdAJRqjFgIplYXWnuVB94sFNF3YTv713xcR8cU92Lbrj2vlhSXg4pdJMlNyl7KlNphkfV%2Ft%2F6kzVO6E7gxBO%2BZDRRZt3iO8r47ECyTqDz%2F3IaZCnD4EuKuR9qB3leNaCo6fGsjpF7LaeWBYkLB6TjXrbooW0q1xwmozY%2Fywv6%2FD3NmpqJHGpGbz53n5JZmkRoGOKVB4L13uJ1kqmhANce8PWJMdKw7GlVgZBMKgQEylZE%2FSpSrUGI3sjwoD3jvuDWeDQpzzvdK0AGRKgi2GLGPgzo25lDkKT%2BNjFWcc6ANLTB9QOLKFF8ZvhA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:49:19,786 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'RwEvecxqLFYpxHdT3sqiRA==', 'Content-Type': 'application/json', 'Content-Length': '3359'}
2023-09-06 21:49:19,786 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:49:57,686 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/47012f79cc6a2c5629c47753decaa244?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wrdfadiHmjHjZrn7Uwr3uy75v2I71xdAJRqjFgIplYXWnuVB94sFNF3YTv713xcR8cU92Lbrj2vlhSXg4pdJMlNyl7KlNphkfV%2Ft%2F6kzVO6E7gxBO%2BZDRRZt3iO8r47ECyTqDz%2F3IaZCnD4EuKuR9qB3leNaCo6fGsjpF7LaeWBYkLB6TjXrbooW0q1xwmozY%2Fywv6%2FD3NmpqJHGpGbz53n5JZmkRoGOKVB4L13uJ1kqmhANce8PWJMdKw7GlVgZBMKgQEylZE%2FSpSrUGI3sjwoD3jvuDWeDQpzzvdK0AGRKgi2GLGPgzo25lDkKT%2BNjFWcc6ANLTB9QOLKFF8ZvhA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:49:57,686 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'RwEvecxqLFYpxHdT3sqiRA==', 'Content-Type': 'application/json', 'Content-Length': '3359'}
2023-09-06 21:49:57,687 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:50:49,696 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/77ly5bjx/wandb-metadata.json?Expires=1694094384&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=R8n5MHAlhJmORTpb%2Fcc3RjjPSKvKbC9XsS6LnVsZdl1zAcI0%2B5cqcsL%2FLqIdlMTUarwnye25myYt7qdRE0MghvoEDGGGnY%2FgeecORooJHzY4eTrL%2BkRFm3LCa3j%2BTgFgPRTxUWhKr1Y4ZUwml5Oy3d1a6CjcPDVdOxOnHULkmFzbDa7r36BNHyFKJLZ%2BLu1aLZvYifXbfrz%2B1%2Bf%2F27N6AFtJeYAAwNKhGH9mKsUHXP%2Byu3C5w5As37VDiT%2FTk8YxaRZVWt18FYaWpJzLswvT%2F0iCudfv52tIdFNj8aIAPkatWM0TBsdjdhFcKeDrOUhowlRNG%2B4rpj3G3%2Bl22l05lQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:50:49,696 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15236'}
2023-09-06 21:50:49,697 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:50:49,697 INFO    wandb-upload_0:32539 [retry.py:__call__():172] Retry attempt failed:
Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 798, in urlopen
    retries = retries.increment(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/retry.py", line 550, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/packages/six.py", line 769, in reraise
    raise value.with_traceback(tb)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 714, in urlopen
    httplib_response = self._make_request(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 403, in _make_request
    self._validate_conn(conn)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connectionpool.py", line 1053, in _validate_conn
    conn.connect()
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/connection.py", line 419, in connect
    self.sock = ssl_wrap_socket(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 449, in ssl_wrap_socket
    ssl_sock = _ssl_wrap_socket_impl(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/urllib3/util/ssl_.py", line 493, in _ssl_wrap_socket_impl
    return ssl_context.wrap_socket(sock, server_hostname=server_hostname)
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 501, in wrap_socket
    return self.sslsocket_class._create(
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1041, in _create
    self.do_handshake()
  File "/root/miniconda3/envs/ling/lib/python3.9/ssl.py", line 1310, in do_handshake
    self._sslobj.do_handshake()
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2491, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/lib/retry.py", line 131, in __call__
    result = self._call_fn(*args, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2520, in upload_file
    raise _e.with_traceback(sys.exc_info()[2])
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/wandb/sdk/internal/internal_api.py", line 2491, in upload_file
    response = self._upload_file_session.put(
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 649, in put
    return self.request("PUT", url, data=data, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/root/miniconda3/envs/ling/lib/python3.9/site-packages/requests/adapters.py", line 501, in send
    raise ConnectionError(err, request=request)
wandb.sdk.lib.retry.TransientError: None
2023-09-06 21:50:54,192 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/77ly5bjx/wandb-metadata.json?Expires=1694094384&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=R8n5MHAlhJmORTpb%2Fcc3RjjPSKvKbC9XsS6LnVsZdl1zAcI0%2B5cqcsL%2FLqIdlMTUarwnye25myYt7qdRE0MghvoEDGGGnY%2FgeecORooJHzY4eTrL%2BkRFm3LCa3j%2BTgFgPRTxUWhKr1Y4ZUwml5Oy3d1a6CjcPDVdOxOnHULkmFzbDa7r36BNHyFKJLZ%2BLu1aLZvYifXbfrz%2B1%2Bf%2F27N6AFtJeYAAwNKhGH9mKsUHXP%2Byu3C5w5As37VDiT%2FTk8YxaRZVWt18FYaWpJzLswvT%2F0iCudfv52tIdFNj8aIAPkatWM0TBsdjdhFcKeDrOUhowlRNG%2B4rpj3G3%2Bl22l05lQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:50:54,192 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15236'}
2023-09-06 21:50:54,192 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:51:03,650 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/47012f79cc6a2c5629c47753decaa244?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wrdfadiHmjHjZrn7Uwr3uy75v2I71xdAJRqjFgIplYXWnuVB94sFNF3YTv713xcR8cU92Lbrj2vlhSXg4pdJMlNyl7KlNphkfV%2Ft%2F6kzVO6E7gxBO%2BZDRRZt3iO8r47ECyTqDz%2F3IaZCnD4EuKuR9qB3leNaCo6fGsjpF7LaeWBYkLB6TjXrbooW0q1xwmozY%2Fywv6%2FD3NmpqJHGpGbz53n5JZmkRoGOKVB4L13uJ1kqmhANce8PWJMdKw7GlVgZBMKgQEylZE%2FSpSrUGI3sjwoD3jvuDWeDQpzzvdK0AGRKgi2GLGPgzo25lDkKT%2BNjFWcc6ANLTB9QOLKFF8ZvhA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:51:03,650 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'RwEvecxqLFYpxHdT3sqiRA==', 'Content-Type': 'application/json', 'Content-Length': '3359'}
2023-09-06 21:51:03,650 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:51:03,885 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/5366b528953a1441ad7f8f84d022595f?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ny2qAF1qTjoHyLPSUQZnpPzfzTwH3AbEtAaCABjB4PV0ayR57v2eg9bvhifVv7VW%2FrdPJ7x%2FNjgo92oFxy48UVCYnZ1NNjFlHbneTFOQUMavHm0A%2FsHcO02w7%2Bsej7WRZxOcLv%2FLE3TqUuzlc0%2BhlOkXyzmrxKDtF4OZ3gYsqHzBq2wbc%2FSjT%2B4OY3gjl54eEdw5SgoZwKpS%2BZVvQNwiBjTALEsByePJRXQM47mDiJpzFCJRdIWASKe%2BYQYfUeSNdJ3qela%2B9XAA6hFNLb9pITMQGRkMjaGc6blyNmDHpFmMjrbywQR%2FLJ4Uty6Z0GfJq1pK24vhDlKjjkWbxY2C1g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:51:03,885 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 21:51:03,885 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:51:12,677 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/5366b528953a1441ad7f8f84d022595f?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ny2qAF1qTjoHyLPSUQZnpPzfzTwH3AbEtAaCABjB4PV0ayR57v2eg9bvhifVv7VW%2FrdPJ7x%2FNjgo92oFxy48UVCYnZ1NNjFlHbneTFOQUMavHm0A%2FsHcO02w7%2Bsej7WRZxOcLv%2FLE3TqUuzlc0%2BhlOkXyzmrxKDtF4OZ3gYsqHzBq2wbc%2FSjT%2B4OY3gjl54eEdw5SgoZwKpS%2BZVvQNwiBjTALEsByePJRXQM47mDiJpzFCJRdIWASKe%2BYQYfUeSNdJ3qela%2B9XAA6hFNLb9pITMQGRkMjaGc6blyNmDHpFmMjrbywQR%2FLJ4Uty6Z0GfJq1pK24vhDlKjjkWbxY2C1g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:51:12,677 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 21:51:12,677 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:53:12,914 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/77ly5bjx/wandb-metadata.json?Expires=1694094384&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=R8n5MHAlhJmORTpb%2Fcc3RjjPSKvKbC9XsS6LnVsZdl1zAcI0%2B5cqcsL%2FLqIdlMTUarwnye25myYt7qdRE0MghvoEDGGGnY%2FgeecORooJHzY4eTrL%2BkRFm3LCa3j%2BTgFgPRTxUWhKr1Y4ZUwml5Oy3d1a6CjcPDVdOxOnHULkmFzbDa7r36BNHyFKJLZ%2BLu1aLZvYifXbfrz%2B1%2Bf%2F27N6AFtJeYAAwNKhGH9mKsUHXP%2Byu3C5w5As37VDiT%2FTk8YxaRZVWt18FYaWpJzLswvT%2F0iCudfv52tIdFNj8aIAPkatWM0TBsdjdhFcKeDrOUhowlRNG%2B4rpj3G3%2Bl22l05lQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:53:12,914 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15236'}
2023-09-06 21:53:12,914 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:53:31,588 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/77ly5bjx/wandb-metadata.json?Expires=1694094384&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=R8n5MHAlhJmORTpb%2Fcc3RjjPSKvKbC9XsS6LnVsZdl1zAcI0%2B5cqcsL%2FLqIdlMTUarwnye25myYt7qdRE0MghvoEDGGGnY%2FgeecORooJHzY4eTrL%2BkRFm3LCa3j%2BTgFgPRTxUWhKr1Y4ZUwml5Oy3d1a6CjcPDVdOxOnHULkmFzbDa7r36BNHyFKJLZ%2BLu1aLZvYifXbfrz%2B1%2Bf%2F27N6AFtJeYAAwNKhGH9mKsUHXP%2Byu3C5w5As37VDiT%2FTk8YxaRZVWt18FYaWpJzLswvT%2F0iCudfv52tIdFNj8aIAPkatWM0TBsdjdhFcKeDrOUhowlRNG%2B4rpj3G3%2Bl22l05lQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:53:31,588 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15236'}
2023-09-06 21:53:31,588 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:53:41,589 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/5366b528953a1441ad7f8f84d022595f?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ny2qAF1qTjoHyLPSUQZnpPzfzTwH3AbEtAaCABjB4PV0ayR57v2eg9bvhifVv7VW%2FrdPJ7x%2FNjgo92oFxy48UVCYnZ1NNjFlHbneTFOQUMavHm0A%2FsHcO02w7%2Bsej7WRZxOcLv%2FLE3TqUuzlc0%2BhlOkXyzmrxKDtF4OZ3gYsqHzBq2wbc%2FSjT%2B4OY3gjl54eEdw5SgoZwKpS%2BZVvQNwiBjTALEsByePJRXQM47mDiJpzFCJRdIWASKe%2BYQYfUeSNdJ3qela%2B9XAA6hFNLb9pITMQGRkMjaGc6blyNmDHpFmMjrbywQR%2FLJ4Uty6Z0GfJq1pK24vhDlKjjkWbxY2C1g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:53:41,589 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 21:53:41,590 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:54:11,570 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/77ly5bjx/wandb-metadata.json?Expires=1694094384&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=R8n5MHAlhJmORTpb%2Fcc3RjjPSKvKbC9XsS6LnVsZdl1zAcI0%2B5cqcsL%2FLqIdlMTUarwnye25myYt7qdRE0MghvoEDGGGnY%2FgeecORooJHzY4eTrL%2BkRFm3LCa3j%2BTgFgPRTxUWhKr1Y4ZUwml5Oy3d1a6CjcPDVdOxOnHULkmFzbDa7r36BNHyFKJLZ%2BLu1aLZvYifXbfrz%2B1%2Bf%2F27N6AFtJeYAAwNKhGH9mKsUHXP%2Byu3C5w5As37VDiT%2FTk8YxaRZVWt18FYaWpJzLswvT%2F0iCudfv52tIdFNj8aIAPkatWM0TBsdjdhFcKeDrOUhowlRNG%2B4rpj3G3%2Bl22l05lQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:54:11,570 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15236'}
2023-09-06 21:54:11,570 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:54:19,494 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/5366b528953a1441ad7f8f84d022595f?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ny2qAF1qTjoHyLPSUQZnpPzfzTwH3AbEtAaCABjB4PV0ayR57v2eg9bvhifVv7VW%2FrdPJ7x%2FNjgo92oFxy48UVCYnZ1NNjFlHbneTFOQUMavHm0A%2FsHcO02w7%2Bsej7WRZxOcLv%2FLE3TqUuzlc0%2BhlOkXyzmrxKDtF4OZ3gYsqHzBq2wbc%2FSjT%2B4OY3gjl54eEdw5SgoZwKpS%2BZVvQNwiBjTALEsByePJRXQM47mDiJpzFCJRdIWASKe%2BYQYfUeSNdJ3qela%2B9XAA6hFNLb9pITMQGRkMjaGc6blyNmDHpFmMjrbywQR%2FLJ4Uty6Z0GfJq1pK24vhDlKjjkWbxY2C1g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:54:19,494 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 21:54:19,494 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:55:21,156 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/77ly5bjx/wandb-metadata.json?Expires=1694094384&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=R8n5MHAlhJmORTpb%2Fcc3RjjPSKvKbC9XsS6LnVsZdl1zAcI0%2B5cqcsL%2FLqIdlMTUarwnye25myYt7qdRE0MghvoEDGGGnY%2FgeecORooJHzY4eTrL%2BkRFm3LCa3j%2BTgFgPRTxUWhKr1Y4ZUwml5Oy3d1a6CjcPDVdOxOnHULkmFzbDa7r36BNHyFKJLZ%2BLu1aLZvYifXbfrz%2B1%2Bf%2F27N6AFtJeYAAwNKhGH9mKsUHXP%2Byu3C5w5As37VDiT%2FTk8YxaRZVWt18FYaWpJzLswvT%2F0iCudfv52tIdFNj8aIAPkatWM0TBsdjdhFcKeDrOUhowlRNG%2B4rpj3G3%2Bl22l05lQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:55:21,156 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15236'}
2023-09-06 21:55:21,156 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:55:21,937 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/47012f79cc6a2c5629c47753decaa244?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wrdfadiHmjHjZrn7Uwr3uy75v2I71xdAJRqjFgIplYXWnuVB94sFNF3YTv713xcR8cU92Lbrj2vlhSXg4pdJMlNyl7KlNphkfV%2Ft%2F6kzVO6E7gxBO%2BZDRRZt3iO8r47ECyTqDz%2F3IaZCnD4EuKuR9qB3leNaCo6fGsjpF7LaeWBYkLB6TjXrbooW0q1xwmozY%2Fywv6%2FD3NmpqJHGpGbz53n5JZmkRoGOKVB4L13uJ1kqmhANce8PWJMdKw7GlVgZBMKgQEylZE%2FSpSrUGI3sjwoD3jvuDWeDQpzzvdK0AGRKgi2GLGPgzo25lDkKT%2BNjFWcc6ANLTB9QOLKFF8ZvhA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:55:21,937 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'RwEvecxqLFYpxHdT3sqiRA==', 'Content-Type': 'application/json', 'Content-Length': '3359'}
2023-09-06 21:55:21,937 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:57:33,554 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/77ly5bjx/wandb-metadata.json?Expires=1694094384&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=R8n5MHAlhJmORTpb%2Fcc3RjjPSKvKbC9XsS6LnVsZdl1zAcI0%2B5cqcsL%2FLqIdlMTUarwnye25myYt7qdRE0MghvoEDGGGnY%2FgeecORooJHzY4eTrL%2BkRFm3LCa3j%2BTgFgPRTxUWhKr1Y4ZUwml5Oy3d1a6CjcPDVdOxOnHULkmFzbDa7r36BNHyFKJLZ%2BLu1aLZvYifXbfrz%2B1%2Bf%2F27N6AFtJeYAAwNKhGH9mKsUHXP%2Byu3C5w5As37VDiT%2FTk8YxaRZVWt18FYaWpJzLswvT%2F0iCudfv52tIdFNj8aIAPkatWM0TBsdjdhFcKeDrOUhowlRNG%2B4rpj3G3%2Bl22l05lQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:57:33,555 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15236'}
2023-09-06 21:57:33,555 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:57:49,541 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/5366b528953a1441ad7f8f84d022595f?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ny2qAF1qTjoHyLPSUQZnpPzfzTwH3AbEtAaCABjB4PV0ayR57v2eg9bvhifVv7VW%2FrdPJ7x%2FNjgo92oFxy48UVCYnZ1NNjFlHbneTFOQUMavHm0A%2FsHcO02w7%2Bsej7WRZxOcLv%2FLE3TqUuzlc0%2BhlOkXyzmrxKDtF4OZ3gYsqHzBq2wbc%2FSjT%2B4OY3gjl54eEdw5SgoZwKpS%2BZVvQNwiBjTALEsByePJRXQM47mDiJpzFCJRdIWASKe%2BYQYfUeSNdJ3qela%2B9XAA6hFNLb9pITMQGRkMjaGc6blyNmDHpFmMjrbywQR%2FLJ4Uty6Z0GfJq1pK24vhDlKjjkWbxY2C1g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:57:49,541 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 21:57:49,541 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 21:59:55,263 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/47012f79cc6a2c5629c47753decaa244?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wrdfadiHmjHjZrn7Uwr3uy75v2I71xdAJRqjFgIplYXWnuVB94sFNF3YTv713xcR8cU92Lbrj2vlhSXg4pdJMlNyl7KlNphkfV%2Ft%2F6kzVO6E7gxBO%2BZDRRZt3iO8r47ECyTqDz%2F3IaZCnD4EuKuR9qB3leNaCo6fGsjpF7LaeWBYkLB6TjXrbooW0q1xwmozY%2Fywv6%2FD3NmpqJHGpGbz53n5JZmkRoGOKVB4L13uJ1kqmhANce8PWJMdKw7GlVgZBMKgQEylZE%2FSpSrUGI3sjwoD3jvuDWeDQpzzvdK0AGRKgi2GLGPgzo25lDkKT%2BNjFWcc6ANLTB9QOLKFF8ZvhA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 21:59:55,264 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'RwEvecxqLFYpxHdT3sqiRA==', 'Content-Type': 'application/json', 'Content-Length': '3359'}
2023-09-06 21:59:55,264 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 22:02:21,917 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/5366b528953a1441ad7f8f84d022595f?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ny2qAF1qTjoHyLPSUQZnpPzfzTwH3AbEtAaCABjB4PV0ayR57v2eg9bvhifVv7VW%2FrdPJ7x%2FNjgo92oFxy48UVCYnZ1NNjFlHbneTFOQUMavHm0A%2FsHcO02w7%2Bsej7WRZxOcLv%2FLE3TqUuzlc0%2BhlOkXyzmrxKDtF4OZ3gYsqHzBq2wbc%2FSjT%2B4OY3gjl54eEdw5SgoZwKpS%2BZVvQNwiBjTALEsByePJRXQM47mDiJpzFCJRdIWASKe%2BYQYfUeSNdJ3qela%2B9XAA6hFNLb9pITMQGRkMjaGc6blyNmDHpFmMjrbywQR%2FLJ4Uty6Z0GfJq1pK24vhDlKjjkWbxY2C1g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 22:02:21,917 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 22:02:21,918 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 22:02:52,823 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/77ly5bjx/wandb-metadata.json?Expires=1694094384&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=R8n5MHAlhJmORTpb%2Fcc3RjjPSKvKbC9XsS6LnVsZdl1zAcI0%2B5cqcsL%2FLqIdlMTUarwnye25myYt7qdRE0MghvoEDGGGnY%2FgeecORooJHzY4eTrL%2BkRFm3LCa3j%2BTgFgPRTxUWhKr1Y4ZUwml5Oy3d1a6CjcPDVdOxOnHULkmFzbDa7r36BNHyFKJLZ%2BLu1aLZvYifXbfrz%2B1%2Bf%2F27N6AFtJeYAAwNKhGH9mKsUHXP%2Byu3C5w5As37VDiT%2FTk8YxaRZVWt18FYaWpJzLswvT%2F0iCudfv52tIdFNj8aIAPkatWM0TBsdjdhFcKeDrOUhowlRNG%2B4rpj3G3%2Bl22l05lQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 22:02:52,823 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15236'}
2023-09-06 22:02:52,823 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 22:05:14,104 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/47012f79cc6a2c5629c47753decaa244?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wrdfadiHmjHjZrn7Uwr3uy75v2I71xdAJRqjFgIplYXWnuVB94sFNF3YTv713xcR8cU92Lbrj2vlhSXg4pdJMlNyl7KlNphkfV%2Ft%2F6kzVO6E7gxBO%2BZDRRZt3iO8r47ECyTqDz%2F3IaZCnD4EuKuR9qB3leNaCo6fGsjpF7LaeWBYkLB6TjXrbooW0q1xwmozY%2Fywv6%2FD3NmpqJHGpGbz53n5JZmkRoGOKVB4L13uJ1kqmhANce8PWJMdKw7GlVgZBMKgQEylZE%2FSpSrUGI3sjwoD3jvuDWeDQpzzvdK0AGRKgi2GLGPgzo25lDkKT%2BNjFWcc6ANLTB9QOLKFF8ZvhA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 22:05:14,104 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'RwEvecxqLFYpxHdT3sqiRA==', 'Content-Type': 'application/json', 'Content-Length': '3359'}
2023-09-06 22:05:14,104 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 22:07:18,056 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/5366b528953a1441ad7f8f84d022595f?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ny2qAF1qTjoHyLPSUQZnpPzfzTwH3AbEtAaCABjB4PV0ayR57v2eg9bvhifVv7VW%2FrdPJ7x%2FNjgo92oFxy48UVCYnZ1NNjFlHbneTFOQUMavHm0A%2FsHcO02w7%2Bsej7WRZxOcLv%2FLE3TqUuzlc0%2BhlOkXyzmrxKDtF4OZ3gYsqHzBq2wbc%2FSjT%2B4OY3gjl54eEdw5SgoZwKpS%2BZVvQNwiBjTALEsByePJRXQM47mDiJpzFCJRdIWASKe%2BYQYfUeSNdJ3qela%2B9XAA6hFNLb9pITMQGRkMjaGc6blyNmDHpFmMjrbywQR%2FLJ4Uty6Z0GfJq1pK24vhDlKjjkWbxY2C1g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 22:07:18,056 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 22:07:18,057 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 22:10:33,296 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/77ly5bjx/wandb-metadata.json?Expires=1694094384&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=R8n5MHAlhJmORTpb%2Fcc3RjjPSKvKbC9XsS6LnVsZdl1zAcI0%2B5cqcsL%2FLqIdlMTUarwnye25myYt7qdRE0MghvoEDGGGnY%2FgeecORooJHzY4eTrL%2BkRFm3LCa3j%2BTgFgPRTxUWhKr1Y4ZUwml5Oy3d1a6CjcPDVdOxOnHULkmFzbDa7r36BNHyFKJLZ%2BLu1aLZvYifXbfrz%2B1%2Bf%2F27N6AFtJeYAAwNKhGH9mKsUHXP%2Byu3C5w5As37VDiT%2FTk8YxaRZVWt18FYaWpJzLswvT%2F0iCudfv52tIdFNj8aIAPkatWM0TBsdjdhFcKeDrOUhowlRNG%2B4rpj3G3%2Bl22l05lQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 22:10:33,296 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15236'}
2023-09-06 22:10:33,296 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 22:10:38,326 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/47012f79cc6a2c5629c47753decaa244?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wrdfadiHmjHjZrn7Uwr3uy75v2I71xdAJRqjFgIplYXWnuVB94sFNF3YTv713xcR8cU92Lbrj2vlhSXg4pdJMlNyl7KlNphkfV%2Ft%2F6kzVO6E7gxBO%2BZDRRZt3iO8r47ECyTqDz%2F3IaZCnD4EuKuR9qB3leNaCo6fGsjpF7LaeWBYkLB6TjXrbooW0q1xwmozY%2Fywv6%2FD3NmpqJHGpGbz53n5JZmkRoGOKVB4L13uJ1kqmhANce8PWJMdKw7GlVgZBMKgQEylZE%2FSpSrUGI3sjwoD3jvuDWeDQpzzvdK0AGRKgi2GLGPgzo25lDkKT%2BNjFWcc6ANLTB9QOLKFF8ZvhA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 22:10:38,326 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'RwEvecxqLFYpxHdT3sqiRA==', 'Content-Type': 'application/json', 'Content-Length': '3359'}
2023-09-06 22:10:38,326 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 22:13:21,368 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/5366b528953a1441ad7f8f84d022595f?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ny2qAF1qTjoHyLPSUQZnpPzfzTwH3AbEtAaCABjB4PV0ayR57v2eg9bvhifVv7VW%2FrdPJ7x%2FNjgo92oFxy48UVCYnZ1NNjFlHbneTFOQUMavHm0A%2FsHcO02w7%2Bsej7WRZxOcLv%2FLE3TqUuzlc0%2BhlOkXyzmrxKDtF4OZ3gYsqHzBq2wbc%2FSjT%2B4OY3gjl54eEdw5SgoZwKpS%2BZVvQNwiBjTALEsByePJRXQM47mDiJpzFCJRdIWASKe%2BYQYfUeSNdJ3qela%2B9XAA6hFNLb9pITMQGRkMjaGc6blyNmDHpFmMjrbywQR%2FLJ4Uty6Z0GfJq1pK24vhDlKjjkWbxY2C1g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 22:13:21,368 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 22:13:21,368 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 22:15:55,925 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/77ly5bjx/wandb-metadata.json?Expires=1694094384&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=R8n5MHAlhJmORTpb%2Fcc3RjjPSKvKbC9XsS6LnVsZdl1zAcI0%2B5cqcsL%2FLqIdlMTUarwnye25myYt7qdRE0MghvoEDGGGnY%2FgeecORooJHzY4eTrL%2BkRFm3LCa3j%2BTgFgPRTxUWhKr1Y4ZUwml5Oy3d1a6CjcPDVdOxOnHULkmFzbDa7r36BNHyFKJLZ%2BLu1aLZvYifXbfrz%2B1%2Bf%2F27N6AFtJeYAAwNKhGH9mKsUHXP%2Byu3C5w5As37VDiT%2FTk8YxaRZVWt18FYaWpJzLswvT%2F0iCudfv52tIdFNj8aIAPkatWM0TBsdjdhFcKeDrOUhowlRNG%2B4rpj3G3%2Bl22l05lQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 22:15:55,925 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15236'}
2023-09-06 22:15:55,926 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 22:16:13,012 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/47012f79cc6a2c5629c47753decaa244?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wrdfadiHmjHjZrn7Uwr3uy75v2I71xdAJRqjFgIplYXWnuVB94sFNF3YTv713xcR8cU92Lbrj2vlhSXg4pdJMlNyl7KlNphkfV%2Ft%2F6kzVO6E7gxBO%2BZDRRZt3iO8r47ECyTqDz%2F3IaZCnD4EuKuR9qB3leNaCo6fGsjpF7LaeWBYkLB6TjXrbooW0q1xwmozY%2Fywv6%2FD3NmpqJHGpGbz53n5JZmkRoGOKVB4L13uJ1kqmhANce8PWJMdKw7GlVgZBMKgQEylZE%2FSpSrUGI3sjwoD3jvuDWeDQpzzvdK0AGRKgi2GLGPgzo25lDkKT%2BNjFWcc6ANLTB9QOLKFF8ZvhA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 22:16:13,013 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'RwEvecxqLFYpxHdT3sqiRA==', 'Content-Type': 'application/json', 'Content-Length': '3359'}
2023-09-06 22:16:13,013 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 22:18:52,530 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/5366b528953a1441ad7f8f84d022595f?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ny2qAF1qTjoHyLPSUQZnpPzfzTwH3AbEtAaCABjB4PV0ayR57v2eg9bvhifVv7VW%2FrdPJ7x%2FNjgo92oFxy48UVCYnZ1NNjFlHbneTFOQUMavHm0A%2FsHcO02w7%2Bsej7WRZxOcLv%2FLE3TqUuzlc0%2BhlOkXyzmrxKDtF4OZ3gYsqHzBq2wbc%2FSjT%2B4OY3gjl54eEdw5SgoZwKpS%2BZVvQNwiBjTALEsByePJRXQM47mDiJpzFCJRdIWASKe%2BYQYfUeSNdJ3qela%2B9XAA6hFNLb9pITMQGRkMjaGc6blyNmDHpFmMjrbywQR%2FLJ4Uty6Z0GfJq1pK24vhDlKjjkWbxY2C1g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 22:18:52,530 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 22:18:52,531 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 22:21:06,730 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-production.appspot.com/chenhaojun001/BitFlip_dqn_with_her/77ly5bjx/wandb-metadata.json?Expires=1694094384&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=R8n5MHAlhJmORTpb%2Fcc3RjjPSKvKbC9XsS6LnVsZdl1zAcI0%2B5cqcsL%2FLqIdlMTUarwnye25myYt7qdRE0MghvoEDGGGnY%2FgeecORooJHzY4eTrL%2BkRFm3LCa3j%2BTgFgPRTxUWhKr1Y4ZUwml5Oy3d1a6CjcPDVdOxOnHULkmFzbDa7r36BNHyFKJLZ%2BLu1aLZvYifXbfrz%2B1%2Bf%2F27N6AFtJeYAAwNKhGH9mKsUHXP%2Byu3C5w5As37VDiT%2FTk8YxaRZVWt18FYaWpJzLswvT%2F0iCudfv52tIdFNj8aIAPkatWM0TBsdjdhFcKeDrOUhowlRNG%2B4rpj3G3%2Bl22l05lQ%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 22:21:06,730 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-Length': '15236'}
2023-09-06 22:21:06,731 ERROR   wandb-upload_0:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 22:21:26,553 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/47012f79cc6a2c5629c47753decaa244?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=wrdfadiHmjHjZrn7Uwr3uy75v2I71xdAJRqjFgIplYXWnuVB94sFNF3YTv713xcR8cU92Lbrj2vlhSXg4pdJMlNyl7KlNphkfV%2Ft%2F6kzVO6E7gxBO%2BZDRRZt3iO8r47ECyTqDz%2F3IaZCnD4EuKuR9qB3leNaCo6fGsjpF7LaeWBYkLB6TjXrbooW0q1xwmozY%2Fywv6%2FD3NmpqJHGpGbz53n5JZmkRoGOKVB4L13uJ1kqmhANce8PWJMdKw7GlVgZBMKgQEylZE%2FSpSrUGI3sjwoD3jvuDWeDQpzzvdK0AGRKgi2GLGPgzo25lDkKT%2BNjFWcc6ANLTB9QOLKFF8ZvhA%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 22:21:26,554 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'RwEvecxqLFYpxHdT3sqiRA==', 'Content-Type': 'application/json', 'Content-Length': '3359'}
2023-09-06 22:21:26,554 ERROR   wandb-upload_2:32539 [internal_api.py:upload_file():2500] upload_file response body: 
2023-09-06 22:24:29,017 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2496] upload_file exception https://storage.googleapis.com/wandb-artifacts-prod/wandb_artifacts/95199606/560663478/5366b528953a1441ad7f8f84d022595f?Expires=1694094394&GoogleAccessId=gorilla-files-url-signer-man%40wandb-production.iam.gserviceaccount.com&Signature=ny2qAF1qTjoHyLPSUQZnpPzfzTwH3AbEtAaCABjB4PV0ayR57v2eg9bvhifVv7VW%2FrdPJ7x%2FNjgo92oFxy48UVCYnZ1NNjFlHbneTFOQUMavHm0A%2FsHcO02w7%2Bsej7WRZxOcLv%2FLE3TqUuzlc0%2BhlOkXyzmrxKDtF4OZ3gYsqHzBq2wbc%2FSjT%2B4OY3gjl54eEdw5SgoZwKpS%2BZVvQNwiBjTALEsByePJRXQM47mDiJpzFCJRdIWASKe%2BYQYfUeSNdJ3qela%2B9XAA6hFNLb9pITMQGRkMjaGc6blyNmDHpFmMjrbywQR%2FLJ4Uty6Z0GfJq1pK24vhDlKjjkWbxY2C1g%3D%3D: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
2023-09-06 22:24:29,017 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2498] upload_file request headers: {'User-Agent': 'python-requests/2.31.0', 'Accept-Encoding': 'gzip, deflate, br', 'Accept': '*/*', 'Connection': 'keep-alive', 'Content-MD5': 'U2a1KJU6FEGtf4+E0CJZXw==', 'Content-Type': 'text/plain; charset=utf-8', 'Content-Length': '3125'}
2023-09-06 22:24:29,017 ERROR   wandb-upload_1:32539 [internal_api.py:upload_file():2500] upload_file response body: 
